houndci/hound

config/style_guides/thoughtbot/scss.yml
Fixes https://app.getsentry.com/hound/production/group/49280598/
=> Add thoughtbot-specific SCSS style guide

app/models/repo_config.rb, spec/models/repo_config_spec.rb
Fixes an error where custom SCSS config wasn't being parsed.
=> Add scss to repo config parser

.gitignore, app/views/application/configuration.haml
We have addressed the reported SCSS bugs during the internal beta with
thoughtbot. It seems like we are ready to open it to the public.
=> Document SCSS support

Gemfile, Gemfile.lock, Rakefile, app/assets/javascripts/application.js, app/assets/javascripts/controllers/account_controller.coffee, app/assets/javascripts/services/credit_card.coffee, app/assets/javascripts/services/stripe_checkout.js.coffee.erb, app/assets/stylesheets/accounts/_show.scss, app/controllers/credit_cards_controller.rb, app/models/payment_gateway_customer.rb, app/views/accounts/show.haml, app/views/application/_settings.haml, app/views/repos/index.haml, config/environments/test.rb, config/routes.rb, spec/controllers/credit_cards_controller_spec.rb, spec/fast_spec_helper.rb, spec/javascripts/controllers/account_controller_spec.coffee, spec/javascripts/spec_helper.coffee, spec/javascripts/support/jasmine.yml, spec/models/payment_gateway_customer_spec.rb, spec/services/repo_subscriber_spec.rb, spec/support/helpers/stripe_api_helper.rb, vendor/assets/javascripts/namespaced.js
This isn't fully built, designed or tested but I wanted to get some early feedback on the approach before getting too far.
=> Use Stripe Checkout to update credit card

.travis.yml
See:
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
https://trello.com/c/6ZvfQ7lg
=> Udpate travis.yml to use container architecture

app/assets/stylesheets/_base.scss
* Add padding to bottom of content element.
=> Make footer easier to view and click

config/application.rb, lib/redirect_to_configuration.rb, spec/features/public_pages_spec.rb
https://twitter.com/just3ws/status/560526236045565952
=> Fix bad params in configuration email

db/migrate/20150130051749_add_index_to_memberships_for_user_id.rb, db/schema.rb
This should make queries in `Analytics` faster.
=> Add index for user_id to memberships

spec/controllers/deactivations_controller_spec.rb, spec/controllers/repos_controller_spec.rb, spec/factories.rb
These were surprising and causing some issues
https://trello.com/c/OC68PeAa
=> Remove factory hooks

Gemfile, Gemfile.lock
So we can use `rails s` to run server
=> Add dotenv gem explicitly

script/rails
=> rm `script/rails`

app/controllers/home_controller.rb, spec/features/repo_list_spec.rb
=> Redirect to repo list when user is signed in and they visit root URL

Gemfile, Gemfile.lock, config/style_guides/ruby.yml, config/style_guides/thoughtbot/ruby.yml, spec/models/style_checker_spec.rb, spec/models/style_guide/ruby_spec.rb
I think I'd like to update the rubocop version on hound-ci to latest version.
What do you think ?
Or, Should we create pull-request for it :question:
=> Update rubocop to latest version

lib/tasks/repo.rake
Based on this comment https://github.com/thoughtbot/hound/pull/622#discussion_r24605555
=> Update `remove_without_memberships` task to only remove inactive repo

lib/tasks/repo.rake
=> Remove `backfill_privacy_and_organization` rake task

config/environments/production.rb
This will fix warnings for production environment
https://trello.com/c/sq2tJ22Q
=> Add log_level for production

app/helpers/application_helper.rb
* To remove not secure resource warning
=> Use https for gravatar image

app/models/style_guide/base.rb, app/services/manage_hound.rb
Since we have `attr_extras` in the project, let's leverage it!
=> Leverage `attr_implement`

config/style_guides/ruby.yml, config/style_guides/thoughtbot/ruby.yml
=> Remove duplicate RuboCop rules

.hound.yml, .ruby-style.yml
This change uses a complete configuration file for Ruby, which includes what is merged by default and a few changes specific to Hound.
=> Add base Ruby style guide

app/models/style_checker.rb, app/models/style_guide/coffee_script.rb, spec/models/style_checker_spec.rb, spec/models/style_guide/coffee_script_spec.rb
=> Lint `coffee.erb` files

app/helpers/configuration_helper.rb, app/views/pages/configuration.haml, config/style_guides/ruby.yml, config/style_guides/scss.yml
This should make it very clear which style guide preferences are used by default and how users can override or disable the defaults.
=> Include links to full configuration files and reword documentation

Gemfile, Gemfile.lock, config/style_guides/scss.yml, config/style_guides/thoughtbot/scss.yml
* Locked to specific version to avoid upgrade problems
* Update configs from scss-lint default file.
=> Upgrade scss lint

app/assets/stylesheets/home/_index.scss, app/views/home/index.haml, app/views/pages/faq.html.haml
* Provide details about bulk pricing in FAQ.
* Group subscription-related questions together.
=> Offer bulk pricing

app/views/pages/faq.html.haml
This change keep language consistent with code.
=> Use activated instead of enabled

.travis.yml, app/models/owner.rb, app/models/style_config.rb, db/migrate/20150220174603_create_style_config.rb, db/schema.rb, spec/models/owner_spec.rb, spec/models/style_config_spec.rb
Part of
https://trello.com/c/V0jY5LWs/452-migrate-existing-config-files-into-database
https://trello.com/c/0kAbrrqi/523-add-table-models-for-configs
=> Adds style_configs table, model, and associations

app/models/repo_config.rb, spec/models/repo_config_spec.rb
https://trello.com/c/hSQ6Xi7l/514-support-rubocop-s-inherit-from
=> Support RuboCop's inherit_from

config/style_guides/thoughtbot/scss.yml
https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertycount
=> Disable SCSS property count linter

app/models/repo_config.rb, app/services/build_runner.rb, config/locales/en.yml, lib/github_api.rb, spec/lib/github_api_spec.rb, spec/models/repo_config_spec.rb, spec/services/build_runner_spec.rb, spec/support/helpers/github_api_helper.rb
https://trello.com/c/QI8TehB7/537-set-github-status-to-failed-when-any-config-files-are-invalid
=> Set GitHub status to failed when a config file is invalid

spec/lib/github_api_spec.rb
- Remove unused variable from GithubApiSpec
=> Fix faulty indentation

app/models/repo_config.rb, app/models/style_guide/java_script.rb, app/views/pages/configuration.haml, spec/models/repo_config_spec.rb, spec/models/style_checker_spec.rb
Kept backwards compatibility with old naming
=> Change javascript and coffeescript keys in hound.yml

app/controllers/subscriptions_controller.rb, spec/controllers/subscriptions_controller_spec.rb
Fixes https://app.getsentry.com/hound-1/production/group/60210071/
https://trello.com/c/t0cytZ8d/565-check-for-presence-of-subscription-before-unsubscribing
=> Check for presence of subscription before unsubscribing

CONTRIBUTING.md, bin/setup
* Update setup docs for local development
* Setup .env file before the database
https://trello.com/c/k4YvjQxP
=> Update development setup and docs

spec/rails_helper.rb
This update removes a `require` statement requiring the current file.
=> Remove unneeded require

config/style_guides/thoughtbot/ruby.yml
Merged into our styleguide as https://github.com/thoughtbot/guides/pull/332
=> Enable nested definitions of classes and methods

config/style_guides/haml.yml, spec/models/style_checker_spec.rb, spec/models/style_guide/haml_spec.rb
We would like to slowly roll out HAML support.
=> Disable all HAML rules for everyone except thoughtbot

config/experiments.yml
Replace loser of last experiment.
https://trello.com/c/UkFQpwoA/574-update-home-page-cta
Results from last experiment:
=> Try "Set Up Hound" for CTA experiment

app/views/application/_analytics.haml, app/views/application/_auth_button.haml
* Delete extra `"` token.
* Add quotes around `variation` property.
=> Fix JavaScript errors

app/assets/javascripts/controllers/account_controller.coffee, app/assets/javascripts/services/account.coffee, app/assets/stylesheets/_button_mixins.scss, app/assets/stylesheets/_buttons.scss, app/assets/stylesheets/accounts/_show.scss, app/assets/stylesheets/application.scss, app/views/accounts/show.haml
* Add form field and submit button for updating the billable email associated with an account
* Update account via Ajax when form is submitted
https://trello.com/c/7MWBmPXN
On page load:
Success:
Failure:
=> Add form for updating billable email

.ruby-style.yml, config/style_guides/thoughtbot/ruby.yml, spec/models/style_guide/ruby_spec.rb
=> Enable trailing comma for thoughtbot

.env, Procfile
This should prevent a busy queue from blocking medium and low queue items.
=> Use separate resque processes for high and medium/low queues

config/locales/en.yml
Why:
* Better documentation makes Hound look well-groomed.
=> Fix a few typos

app/models/bulk_customer.rb, app/models/plan.rb, app/models/repo.rb, db/migrate/20150725013530_create_bulk_customers.rb, db/schema.rb, spec/factories.rb, spec/models/bulk_customer_spec.rb, spec/models/plan_spec.rb, spec/models/repo_spec.rb, spec/spec_helper.rb
This makes it easier to add and manage new bulk customers.
We can build on this to make it even simpler.
=> Store bulk customer data in the database

config/application.rb, config/initializers/cookies_serializer.rb, config/initializers/filter_parameter_logging.rb
This helps when upgrading Rails versions
=> Structure files according to used version of rails

Gemfile.lock
Changes:
- Improved UI
- Fixed a bug where editing files in development would require you to
restart the server
For full changes, see
https://github.com/thoughtbot/administrate/blob/9cbdd5abf0dc53dd787f09afb7ee7dd133936ec7/administrate/NEWS
Tags: #ruby
=> Upgrade Administrate to v0.0.9

app/models/style_guide/base.rb, app/models/style_guide/coffee_script.rb, app/models/style_guide/python.rb, app/models/style_guide/scss.rb, app/models/style_guide/swift.rb, spec/models/style_guide/python_spec.rb, spec/models/style_guide/scss_spec.rb, spec/models/style_guide/swift_spec.rb, spec/models/style_guide/test_spec.rb
References https://github.com/thoughtbot/hound/pull/913#discussion_r38964659
=> Define `file_included?` in `StyleGuide::Base`

app/views/pages/configuration.haml
Since we announced the beta, we should have some information about it.
=> Add Python documentation

spec/models/linter/base_spec.rb, spec/models/linter/coffee_script_spec.rb, spec/models/linter/go_spec.rb, spec/models/linter/haml_spec.rb, spec/models/linter/java_script_spec.rb, spec/models/linter/python_spec.rb, spec/models/linter/ruby_spec.rb, spec/models/linter/scss_spec.rb, spec/models/linter/swift_spec.rb, spec/models/linter/unsupported_spec.rb, spec/models/pull_request_spec.rb, spec/support/helpers/configuration_helper.rb, spec/support/helpers/style_guide_helper.rb
To follow up on https://github.com/thoughtbot/hound/pull/924
=> Replace `style_guide` with `linter`

CONTRIBUTING.md
Explains the data requirements around the inbound and outbound queues.
Inbound arguments extracted from [this comment][inbound].
Outbound arguments extracted from [this method][outbound].
[inbound]: https://github.com/thoughtbot/hound-markdown/blob/a4a10311825c1dc87b4845476833a2f386c8f8ca/lib/jobs/markdown_review_job.rb#L8-L15
[outbound]: https://github.com/thoughtbot/hound-markdown/blob/a4a10311825c1dc87b4845476833a2f386c8f8ca/lib/jobs/markdown_review_job.rb#L23-L28
=> Document the API for custom Linters

spec/models/linter/ruby_spec.rb
As suggested in
https://github.com/thoughtbot/hound/pull/950#discussion_r41444874
=> Properly indent here-docs

app/models/config/base.rb, spec/models/config/base_spec.rb, spec/services/build_runner_spec.rb
Should address https://app.getsentry.com/hound-1/production/group/88432966/.
=> Handle missing linter configuration

app/models/owner.rb, app/models/style_config.rb, db/migrate/20151019123908_remove_style_config.rb, db/schema.rb, spec/models/owner_spec.rb, spec/models/style_config_spec.rb
We decided not to save the configuration in the database.
https://trello.com/c/pDvJ8BbS
=> Remove `StyleConfig`

spec/models/style_checker_spec.rb
A follow-up on https://github.com/thoughtbot/hound/pull/985#discussion_r44134857
=> Rename service based linter test descriptions

app/helpers/configuration_helper.rb, app/views/pages/configuration.haml
- Sort the Table of Contents for the different languages and linters.
=> Document how to configure EsLint

app/jobs/report_invalid_config_job.rb, app/models/commit_status.rb, app/services/report_invalid_config.rb, spec/jobs/report_invalid_config_job_spec.rb, spec/models/commit_status_spec.rb, spec/services/report_invalid_config_spec.rb
=> Allow a custom message to be given to `ReportInvalidConfigJob`

app/models/config/base.rb, app/models/linter/base.rb, app/services/check_enabled_linter.rb, spec/models/linter/base_spec.rb, spec/services/check_enabled_linter_spec.rb
To see which linters the config has enabled.
Changes:
- Extract `build_linter`.
=> Extract `LinterEnabledChecker`

app/services/rebuild_pull_request.rb, spec/services/rebuild_pull_request_spec.rb
* Add `Rebuilder` to trigger a new build from an existing build for a
repo and pull request number.
https://trello.com/c/hVwHmtpP
=> Add service to run a rebuild

app/views/home/index.haml
=> Fix home page grammatical issue

app/assets/images/languages/python.svg, app/assets/images/languages/swift.svg, app/views/home/index.haml
=> Add swift and python language icons for home page

Gemfile, Gemfile.lock, app/serializers/repo_serializer.rb
=> Upgrade ActiveModelSerializers

app/assets/stylesheets/repos/_index.scss, app/assets/stylesheets/repos/_organization.scss
The repos grouped by organization is merged and functional, but there is probably room for improvement of the UX on that page.
Card with suggestions:
https://trello.com/c/uTdmx2Ga
=> WIP: Polish up repos page

app/assets/stylesheets/_base.scss, app/assets/stylesheets/_button_mixins.scss, app/assets/stylesheets/_toggle_switch.scss, app/assets/stylesheets/_variables.scss, app/assets/stylesheets/accounts/_show.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/application/_header.scss, app/assets/stylesheets/home/_index.scss, app/assets/stylesheets/pages/_builds.scss, app/assets/stylesheets/pages/_pages.scss, app/assets/stylesheets/repos/_index.scss, app/assets/stylesheets/repos/_tools.scss, app/assets/stylesheets/sessions/_new.scss, app/views/pages/builds.html.haml
I didn't commit the changes to the `routes` that would be needed to view this page, figured we'd want to keep it hidden
* Refactor font-weight
* Refactor transitions
* Add spacing variables
* Build Builds page with static content
https://trello.com/c/FLrhuBGo
=> Add static Builds page so users can rerun a build

app/queries/recent_builds_by_repo_query.rb
The recent builds query was... not great. The columns used for the
dense ranking partially covered by two indexes, but it wasn't a close
enough match for the query analyzer to use them. To keep the same query,
I think we'd want to add an index specifically for it, which would be
something like `ON (repo_id, pull_request_number, created_at DESC)`.
That seems a bit much to me, especially given that our `builds` sees a
lot of writes.
This commit completely replaces the query with a different one, making
use of `distinct on` to get the most recent build for each repo+pr. The
performance is quite a bit better, but is way more verbose.
```
Limit  (cost=1371574.44..1371574.44 rows=1 width=770) (actual time=22822.321..22822.330 rows=20 loops=1)
->  Sort  (cost=1371574.44..1371574.44 rows=1 …
```
=> Performance tune the recent builds query

app/models/linter/ruby.rb, spec/models/linter/ruby_spec.rb
https://github.com/houndci/hound/issues/1174
=> Lint RAKE file extension with Ruby

app/assets/stylesheets/base/_variables.scss, app/assets/stylesheets/components/_header.scss, app/assets/stylesheets/pages/_docs.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/repos/_index.scss, app/assets/stylesheets/pages/repos/_onboarding.scss, app/assets/stylesheets/pages/repos/_organization.scss, app/assets/stylesheets/pages/repos/_tools.scss, app/assets/stylesheets/pages/sessions/_new.scss, app/views/pages/configuration.haml, app/views/pages/faq.html.haml
* Screen sizes, variables, and media queries
* Border variables
* Use classes instead of indenting
* List and Navigation styles
=> Refactor Docs/FAQ SCSS

app/assets/javascripts/components/repo.js.jsx, app/assets/javascripts/components/repo_allowance.js.jsx, app/assets/javascripts/components/repo_deactivation_button.js.jsx, app/assets/javascripts/components/repos_container.js.jsx, app/assets/stylesheets/pages/repos/_index.scss, app/serializers/user_serializer.rb, app/views/application/_header.haml, spec/controllers/users_controller_spec.rb, spec/factories.rb, spec/features/listing_pricings_spec.rb, spec/features/user_activates_a_repo_spec.rb, spec/features/user_deactivates_a_repo_spec.rb, spec/serializers/user_serializer_spec.rb
Previously, the header was only updated with the latest tier information when the user refreshed the page, which meant it was not obvious to the user what the current state of their payment plan was. Updated the activation and deactivation logic to update the allowance element in the header appropriately.
https://trello.com/c/EJLrc4J5
=> Update header with tier information

app/assets/javascripts/components/__tests__/upgrade_subscription_link-test.jsx, app/assets/javascripts/components/notify_tier_change.jsx, app/assets/javascripts/components/repos_container.jsx, app/assets/javascripts/components/upgrade_subscription_link.jsx, app/assets/javascripts/lib/ajax.jsx, app/controllers/subscriptions_controller.rb, app/models/tier.rb, app/views/pricings/index.html.erb, spec/features/user_activates_a_repo_spec.rb, spec/models/tier_spec.rb
Before, we showed people without a registered card a form without any explanation. We felt this was confusing. Updated the activation button to redirect people to "Pricings" for more information.
=> Show "Pricings" for first activation

app/views/pages/configuration.haml
- more info on Go linting
- adds info on TS and Elixir linting
=> Adds info on beta linters, re-orders the markup to match TOC layout

app/views/accounts/show.haml, app/views/shared/_plan_vertical.html.erb, config/locales/en.yml
We no longer have bulk plans after moving to tiered pricing.
Unlimited plan is only for public repos ;)
=> Remove bulk plans mention + clarify unlimited

CONTRIBUTING.md
Add new linters, restructure a bit and update links.
=> Update info about inters in CONTRIBUTING doc

.hound.yml, .rubocop.yml, app/jobs/stylelint_review_job.rb, app/models/linter/stylelint.rb, spec/models/linter/stylelint_spec.rb
This will be the first linter to officially use the single `linters`
queue.
=> Use linters queue for stylelint

app/controllers/activations_controller.rb, app/models/repo.rb, app/serializers/repo_serializer.rb, spec/factories.rb, spec/features/user_activates_a_repo_spec.rb
We accidentally removed this feature as part of a previous commit that
did some load times optimizations.
=> Allow bulk subscribers to enable repos

app/assets/stylesheets/base/_typography.scss, app/assets/stylesheets/base/_variables.scss, app/assets/stylesheets/components/_code.scss, app/assets/stylesheets/pages/home/_home-languages.scss
Use global variables in a more expected fashion and group them together.
=> Refactor base typography Sass

README.md
=> List all supported languages in README

app/assets/stylesheets/admin/administrate.scss, app/views/admin/job_failures/index.haml, config/initializers/administrate.rb
=> Fix Job Failures layout in Administrate

app/assets/javascripts/application.js
This fixes the [Stop Masquerading](https://github.com/houndci/hound/blob/150d791c056d870c80feb5b7f609be45499ae5d0/app/views/application/_app_nav.haml#L39) link.
=> Restore jquery-ujs to support delete links

app/assets/stylesheets/pages/accounts/_show.scss, app/javascript/__tests__/__snapshots__/update_account_email-test.jsx.snap, app/javascript/components/UpdateAccountEmail/components/App.jsx, app/models/user.rb, app/serializers/user_serializer.rb, app/views/accounts/show.haml, app/views/plans/index.html.haml, app/views/repos/index.haml
* Validate email address submission
* Style Update Email button
=> Account page updates

.rubocop.yml, app/assets/stylesheets/base/_variables.scss, app/assets/stylesheets/pages/repos/_index.scss, app/controllers/subscriptions_controller.rb, app/javascript/__tests__/upgrade_subscription_link-test.jsx, app/javascript/components/NotifyTierChange/components/App.jsx, app/javascript/components/NotifyTierChange/components/UpgradeSubscriptionLink.jsx, app/services/repo_subscriber.rb, spec/controllers/subscriptions_controller_spec.rb, spec/services/repo_subscriber_spec.rb
Prompt user for their payment info when their upgrade fails.
=> Upgrade with new payment information

lib/github_api.rb, spec/support/helpers/github_api_helper.rb
=> Capitalize hound in status

app/models/config_content.rb, app/services/build_runner.rb, app/services/resolve_config_conflicts.rb, spec/models/config/haml_spec.rb, spec/models/config/rubocop_spec.rb, spec/models/config_content_spec.rb, spec/services/build_runner_spec.rb, spec/services/resolve_config_conflicts_spec.rb
* Avoid `NoMethodError: undefined method `[]' for nil:NilClass`
=> Handle nil options when resolving config conflicts

app/javascript/components/NotifyTierChange/components/UpgradeSubscriptionLink.jsx, app/javascript/components/ReposContainer/components/App.jsx
* This replaces the basic alert
=> Open Intercom when repo activation fails

.hound.yml, .reek
We should eat our own dog food.
=> Enable Reek, Flog and Flay

config/environments/production.rb
I'm sending the PR as discussed in #1511.
=> Allow setting serve static files with env

Gemfile.lock, app/models/commit_status.rb, app/models/owner.rb, app/services/build_runner.rb, config/locales/en.yml, db/migrate/20180613230247_add_stripe_subscription_id_to_owners.rb, db/schema.rb, lib/github_api.rb
=> Use status to notify customers when their payment fails

README.md
=> Add Hound badge

app/models/github_event.rb, spec/models/github_event_spec.rb, spec/support/fixtures/github_app_uninstall.json, spec/support/fixtures/github_installation_repositories_added.json, spec/support/fixtures/github_installation_repositories_removed.json
https://developer.github.com/v3/activity/events/types/#installationrepositoriesevent
=> Handle App uninstallation and updates

app/views/home/index.haml
=> Add a signin button below Pricing section

app/models/commit.rb, app/models/config/rubocop.rb, app/models/linter/base.rb, spec/models/config/rubocop_spec.rb
To see if anyone is still using old configs.
=> Notify us of any legacy configs

app/jobs/completed_file_review_job.rb
This reverts commit f2e43d07959fcb012a7e32780fb080ad6412f071.
=> Revert "Retry when completed file reviews fail (#1619)"

README.md
I noticed a couple of the languages in CONTRIBUTING.md weren't in the
readme. This commit also includes some formatting changes to make it
easier to see if a language is supported.
=> Add additional languages

app/views/application/_app_nav.haml, app/views/home/_get_started_cta.haml, app/views/home/_original.haml, app/views/home/_simple.haml
=> Update public navigation

Gemfile.lock
Bunlder audit detected a vulnerability
=> Update Nokogiri for security

spec/features/repo_list_spec.rb
Ensure user in the test has an active repo, to fulfill all of the
condition prerequisites.
=> Fix intermittent test failure

app/controllers/application_controller.rb
@gylaz this should help us associate signups with ad clicks.
=> Save Google click IDs

Gemfile.lock, app/assets/stylesheets/components/_pricing.scss, app/assets/stylesheets/pages/accounts/_show.scss, app/models/metered_stripe_plan.rb, app/models/owner.rb, app/models/payment_gateway_customer.rb, app/models/plan_selector.rb, app/models/user.rb, app/presenters/account_page.rb, app/views/accounts/show.haml, app/views/application/_app_nav.haml, app/views/plans/_private.html.haml, app/views/shared/_plan_vertical.html.haml, spec/models/plan_selector_spec.rb, spec/presenters/account_page_spec.rb
=> Update account page to show review based plan info

app/models/metered_stripe_plan.rb
=> Add yearly plan reference

Gemfile.lock, package.json, yarn.lock
For more recent `bundler` versions, we need to apply a fix for Heroku deploys.
=> Fix the bundler issue of deploying to Heroku
