app/policies/commenting_policy.rb
spec/policies/commenting_policy_spec.rb

When fetching comments on a pull request, the GitHub api includes two values indicating the position of the comment in the patch: `position` and `original_position`. Most of the time, `position` is nil, and `original_position` contains the relevant value. However, if an event causes the patch to change, e.g. a new commit is pushed, both `position` and `original_position` will contain values. This change looks for the presence of `position`, using it for the comparison when appropriate.
I have found basically no documentation about the semantics of these two values. From the cases I've looked at, it appears that the values are swapped. It seems appropriate to me that `position` would be the present value that majority of the time, and `original_position` would only exist when something …

Account for comments that change patch position

---

db/migrate/20141219224840_inactivate_repos_without_privacy_or_org_info.rb
db/schema.rb
lib/tasks/repo.rake

* Inactivate repositories which lack privacy or org information
* Add rake task to update repo information
https://trello.com/c/oPFtmreZ/393-builds-are-being-run-for-active-repos-missing-privacy-and-organization-information

Handle repos with inadequate information

---

app/assets/stylesheets/_account.scss
app/assets/stylesheets/_repo-list.scss

Fixes styles in account breakdowns page
Fixes styles for ui toggle
---------
BEFORE
AFTER

Fix toggle and account breakdowns styles

---

.sample.env
README.md
bin/setup
config/initializers/sentry.rb

* Use ngrok for GitHub app.
* Get Stripe tokens automatically from staging in `bin/setup`.

Improve local Hound instructions

---

app/models/repo.rb
app/services/repo_synchronization.rb
db/migrate/20150108003045_add_uniqueness_on_full_github_name_to_repos.rb
db/schema.rb
spec/models/repo_spec.rb

* add a uniquness constraint on `full_github_name`
* attempt to find the repo based on name first, then by id, then update it
https://trello.com/c/2Kl8oLFV

Ensure uniqueness of repository name

---

app/models/commit.rb
spec/models/commit_spec.rb

GitHub will error when a file is over 1MB.
https://app.getsentry.com/hound-1/production/group/49620125/

Handle GitHub error when file is too large to fetch

---

doc/SECURITY.md
lib/github_api.rb
spec/models/github_user_spec.rb
spec/support/helpers/github_api_helper.rb

In order to create/update commit statuses for repositories belonging to an organization, the *Services* team needs **push** access.  No change is required for user owned repositories, because *houndci* is added as a collaborator, which includes push access.
Does this warrant an update to the [security] doc? The relevant section mentions the *Services* team, but it doesn't call out the access level.
https://trello.com/c/Z3GpdyNn
[security]: https://github.com/thoughtbot/hound/blob/b8a1169f0f25a33f04cbb5c75fb83d2edbf89d9d/doc/SECURITY.md#what-happens-when-you-enable-hound-on-your-github-repository

Create team with push permissions

---

doc/SECURITY.md

Previously clicking on the `security@` email link would open https://github.com/thoughtbot/hound/blob/master/doc/security@thoughtbot.com, which 404's.  Now it opens a mail client.

Update email link in SECURITY

---

config/initializers/resque.rb

Attempt to fix:
```
could not receive data from client: Connection reset by peer
```
As per [Heroku docs][1].
[1]: https://devcenter.heroku.com/articles/forked-pg-connections#resque-ruby-queuing

Cleanup db connections for Resque workers

---

lib/github_api.rb
spec/lib/github_api_spec.rb
spec/support/fixtures/org_teams_with_lowercase_services_team.json
spec/support/fixtures/org_teams_with_pull_permission_services_team.json
spec/support/fixtures/team_update.json
spec/support/helpers/github_api_helper.rb

Teams created before 855e932 will only have *pull* permission, leaving hound unable to update pull request statuses for repositories of that organization. This change adds a check for *pull* only access during repository activation, and will upgrade the Services team to *push* permission.
I updated the existing team fixtures to have "push" access, to avoid having to stub the update team requests for every spec. I tried to keep the names for the new requests/fixtures in-line with what was there, but they feel cumbersome. If anyone has suggestions for better ones, I'd love to hear them.
https://trello.com/c/kdFGneUh

Update pull permission teams to push permission

---

app/models/style_guide/scss.rb
spec/models/style_guide/scss_spec.rb

The SCSS linter stores violations in an [instance variable][omg-state], and doesn't clear them between runs or provide a public interface for clearing them. This led to erroneous violations being reported on files when a violation in another file happened to be on the same line number that's included in the diff.
This change uses a newly created linter for every file that's checked, in order to avoid the responsibility of clearing the state between each run.
I think the name/phrasing in the spec need some work, but I'm unable to come up with something better at the moment. Anyone have any suggestions?
Will close #562
https://trello.com/c/qObHGpDB
[omg-state]: https://github.com/causes/scss-lint/blob/8319483e3686e1956613069e6a02a56e62db74bc/lib/scss_lint/runner.rb#L12

Fix SCSS linter creating erroneous violations

---

app/services/add_hound_to_repo.rb
app/services/repo_activator.rb
lib/github_api.rb
spec/features/repo_list_spec.rb
spec/lib/github_api_spec.rb
spec/services/add_hound_to_repo_spec.rb
spec/services/repo_activator_spec.rb
spec/support/helpers/github_api_helper.rb

Extract the logic out of the `GithubApi` into a service. `GithubApi` should
only be a wrapper over Octokit methods and not handle complex logic.
This allows us to test that logic easier in isolation without stubbing
external requests.

Move logic of adding Hound to an repo

---

app/views/accounts/show.haml
spec/features/account_spec.rb

This avoids a potential issue where a users without subscriptions, or Stripe Customer set up, updates their card info for some reason.
I think it happened once already.
https://twitter.com/IanWalter/status/561265511133351936

Hide credit card link if Stripe customer hasn't been set up

---

app/assets/javascripts/directives/repo.js.coffee.erb
app/models/report.rb
app/serializers/user_serializer.rb
app/services/repo_subscriber.rb
spec/controllers/users_controller_spec.rb
spec/services/repo_subscriber_spec.rb

This change skips Stripe Checkout when a card has already been entered. I also added some view logic to not show the "Update Credit Card" link if no Stripe customer exists.

Don't prompt user for credit card if one has already been set up

---

app/views/application/_segment_io.haml
app/views/shared/_auth_button.haml

Find out how many people click, but then drop out of the funnel because they
think the GitHub permissions are too aggressive.

Track "Clicked Sign In" event

---

app/controllers/activations_controller.rb
app/controllers/deactivations_controller.rb
app/controllers/subscriptions_controller.rb
app/models/analytics.rb
app/services/build_runner.rb
spec/controllers/activations_controller_spec.rb
spec/controllers/deactivations_controller_spec.rb
spec/controllers/subscriptions_controller_spec.rb
spec/services/build_runner_spec.rb

* "Reviewed Repo" is not reporting correctly to Segment/Mixpanel.
* We already have build totals in the North Star Metric.
* Since "Reviewed Repo" is not useful to us, right now,
we can try a more constrained event tracking approach.
* Track only private (subscribed) repos.
* Track both a "Build Started" and a "Build Completed" event
to see if there is some code in between that is preventing
the "Reviewed Repo" (now called "Build Completed") event
from triggering.

Track "Build Started" and "Build Completed" events

---

Gemfile.lock

Fixes:
> DEPRECATION WARNING: The configuration option
> `config.serve_static_assets` has been renamed to
> `config.serve_static_files` to clarify its role
> (it merely enables serving everything in the `public` folder
> and is unrelated to the asset pipeline).
> The `serve_static_assets` alias will be removed in Rails 5.0.
> Please migrate your configuration files accordingly.

Upgrade rails_serve_static_assets for Rails 4.2.0

---

app/models/commit.rb
spec/models/commit_spec.rb

It appears that sometimes there are no errors associated with an Octokit 
exception as show by:
https://app.getsentry.com/hound-1/production/group/53642463/
This fix checks for presense of an error before fetching `:code` from it.

Check if Octokit exception contains errors

---

app/jobs/accept_org_invitations_job.rb
app/jobs/repo_information_job.rb
app/models/pull_request.rb
app/services/build_runner.rb
app/services/repo_activator.rb
lib/github_api.rb
spec/jobs/accept_org_invitations_job_spec.rb
spec/lib/github_api_spec.rb
spec/models/github_user_spec.rb
spec/services/build_runner_spec.rb
spec/services/repo_activator_spec.rb

- Rename `OrgInvitationJob` to `AcceptOrgInvitationsJob`
- Be explicit that it accepts the org invitations, not sending them
- Explicitly provide github token to `GithubApi`

Refactor invitation to organization

---

app/jobs/buildable.rb
app/models/default_config_file.rb
app/models/owner.rb
app/models/payload.rb
app/models/pull_request.rb
app/models/repo.rb
app/models/style_checker.rb
app/models/style_guide/base.rb
app/models/style_guide/coffee_script.rb
app/models/style_guide/java_script.rb
app/models/style_guide/ruby.rb
app/models/style_guide/scss.rb
app/services/repo_synchronization.rb
db/migrate/20141211224528_create_owners.rb
db/migrate/20150123224104_add_owner_to_repos.rb
db/schema.rb
lib/github_api.rb
spec/factories.rb
spec/jobs/buildable_spec.rb
spec/models/owner_spec.rb
spec/models/payload_spec.rb
spec/models/repo_spec.rb
spec/models/style_checker_spec.rb
spec/models/style_guide/coffee_script_spec.rb
spec/models/style_guide/java_script_spec.rb
spec/models/style_guide/ruby_spec.rb
spec/models/style_guide/scss_spec.rb
spec/services/repo_synchronization_spec.rb

This PR updates the `RepoSynchronization` process and `Build`'s to assign the
`repo` to its parent `owner` (which is either a user or an organization). Tying
the `repo` to the `owner` is a preliminary step to having `owner` level
configuration.
New `repo`'s and updated `repo`'s (updated via the user clicking 'Refresh Repo
List' or via a build) will have their `owner`s populated.  We'll need to
backfill the `repo`'s that are not new and are not refreshed. I propose we merge
this PR as is and then have follow up work that adds an idempotent rake task
(which requires calls to GitHub) that will backfill `repo`'s missing
`owner_id`'s. Once the data is backfilled, we can apply a `null: false`
constraint to `repos.owner_id`.
Part of
https://trello.com/c/V0jY5LWs/452-migrate-existing-config-files- …

Adds owners tables and 	assigns owner in repo creation / update

---

app/assets/javascripts/directives/repo.js.coffee.erb
app/controllers/activations_controller.rb
app/services/repo_activator.rb
lib/error_message_translation.rb
spec/controllers/activations_controller_spec.rb
spec/lib/error_message_translation_spec.rb
spec/services/repo_activator_spec.rb

* Currently when repo activation fails a generic error message
is displayed to the user. This commit introduces support for
displaying detailed, actionable error messages when repo activation fails.
* Update `RepoActivator` to add and expose errors when repo activation
fails due to a GitHub permissions issue.
* Update `ActivationsController#create` to return error messages when
error messages are present.
* Introduce `ErrorMessageTranslation` to handle translating
non-user-friendly Octokit error messages into messages that can be
displayed to the end user.
* Update client-side error handling to display error messages included
in response body
* https://trello.com/c/KYuTdbXS/405-when-a-user-tries-to-enable-a-repo-and-it-fails-they-get-no-feedback-as-to-why-enabling-the-repo-failed

Display detailed error message if activation fails

---

app/jobs/buildable.rb
app/services/build_runner.rb
spec/jobs/buildable_spec.rb
spec/services/build_runner_spec.rb

Hound receives payloads for events that aren't the PullRequest payloads we care
for. Thus, moving this into `BuildRunner#run` ensures the payload is relevant.
Related error: https://app.getsentry.com/hound-1/production/group/54752935/

Move Owner.upsert to BuildRunner

---

app/jobs/accept_org_invitations_job.rb
app/jobs/buildable.rb
app/jobs/repo_information_job.rb
app/jobs/repo_synchronization_job.rb
spec/jobs/accept_org_invitations_job_spec.rb
spec/jobs/buildable_spec.rb
spec/jobs/repo_information_job_spec.rb
spec/jobs/repo_synchronization_job_spec.rb

Instead send the parameters that might be interesting for the exception,
i.e `user_id`, `payload_data` etc.

Scrub parameters before sending exception to Sentry

---

lib/github_api.rb
spec/lib/github_api_spec.rb

This should help us avoid hitting our rate limit by not making multiple requests to GitHub for the same file content.

Cache file content requested from GitHub

---

app/controllers/builds_controller.rb
app/models/payload.rb
spec/controllers/builds_controller_spec.rb
spec/models/payload_spec.rb
spec/support/fixtures/push_event.json

Don't schedule jobs for payloads that are not for a pull request
(e.g. commit push). No reason to waste the backround job round trip just to
do nothing.

Ignore non-pr payloads

---

app/jobs/retryable.rb

Most of the failures we get are network problems. We shouldn't wait long to
retry jobs anyhow.

Reduce the wait time between failed jobs

---

app/models/style_guide/coffee_script.rb
spec/models/style_guide/coffee_script_spec.rb

This happens when the file refers to variables or methods outside of
it's scope.
https://app.getsentry.com/hound-1/production/group/55884035/

Swallow erb exceptions when parsing `coffee.erb`

---

app/services/build_runner.rb
spec/services/build_runner_spec.rb

Given a PR with violations in the diff, if `MAX_COMMENTS` is not set Hound will not report any violations. This is a kind of silent failure, which I think we should avoid.

Read MAX_COMMENTS using ENV#fetch

---

db/migrate/20150225001118_add_unique_index_on_subscription_repo_id.rb
db/schema.rb
spec/models/subscription_spec.rb

To prevent duplicate subscription records (and charges) for the same repo. Use a
unique partial index since we don't care for it to be unique if it was deleted.

Add a unique index on `subscriptions` `repo_id`

---

README.md

Github's markdown formatter was displaying the ngrok URLs incorrectly
because of the angle brackets. This commit surrounds the URLs with
backticks so they display as preformatted text.

README: Display correct ngrok URLs on GitHub

---

app/models/repo_config.rb

There's a vulnerability in `YAML.load` which can enable arbitrary code to be run
on our sytems. `YAML.safe_load` does not deserialize unsafe classes.
Related reading:
http://blog.codeclimate.com/blog/2013/01/10/rails-remote-code-execution-vulnerability-explained/
https://github.com/tenderlove/psych/issues/119
http://docs.ruby-lang.org/en/2.1.0/Psych.html#method-c-safe_load

Use YAML.safe_load when loading custom config

---

config/style_guides/ruby.yml

We are testing these complexity cops out on Hound itself, I would rather wait until we have some feedback before enabling them for everyone by default.

Disable PerceivedComplexity cop

---

app/models/repo_config.rb
spec/models/repo_config_spec.rb

The RuboCop config uses a Ruby regex line in the config
Related error:
https://app.getsentry.com/hound-1/production/group/56103505/

Whitelist Regexp for yaml loading

---

app/services/build_runner.rb
config/locales/en.yml
spec/services/build_runner_spec.rb
spec/support/helpers/github_api_helper.rb

This change is meant to liven up the status messages used on GitHub.

Update status messages

---

app/controllers/repos_controller.rb
spec/controllers/repos_controller_spec.rb

Currently, it is possible for there to be duplicate `memberships` tying a `user`
to `repos` and as a result, the user can sometimes see duplicate `repos` on
houndci.com. This update solves the UI problem. We'll have to dig a bit deeper
to figure out where the duplicates are coming from in the first place.
Part of
https://trello.com/c/GnvVhljg/532-repos-json-endpoint-returns-duplicate-repos

Return unique list of repos from repos.json

---

app/controllers/repo_syncs_controller.rb
spec/controllers/repo_syncs_controller_spec.rb

This update allows for the user's repo filtering to work after synced repos get
loaded up again.
https://trello.com/c/6RlXlvgP/529-show-repos-after-searching-and-refreshing

Set user.refreshing_repos to true

---

app/services/repo_activator.rb
spec/services/repo_activator_spec.rb

If removing @houndci from the organization and repo fails for some reason, we
don't care, as we just want to make sure the hook is removed and the repo is
deactivated.

Ignore return status of deactivation cleanup

---

app/controllers/builds_controller.rb
spec/controllers/builds_controller_spec.rb

Somehow this was lost during the switch to `ActiveJob`.

Use only the data required for builds in jobs

---

app/services/build_runner.rb
spec/services/build_runner_spec.rb

If the repo has been transfered, this will be picked up during a build. Also,
this will populate our empty `repo.owner_id` fields.

Update repo owner on each build

---

app/assets/stylesheets/repos/_index.scss

Turns out, the CPU load was caused by the many animated spinners that
are hidden on the page at any given time. Every repo has a spinner
that's only shown when it's being activated or deactivated.
With `visibility: hidden`, the browser was still animating these
spinners even when they weren't visible. You can see that in the Chrome
devtools by selecting a `.repo::before` pseudo-element, and you'll see a
spinning outline of where the component is hidden.
One problem with using `display: none` (the new approach) is that the
gear icon is not loaded until someone clicks on 'Activate' or
'Deactivate'. That shows up as a small delay, but I'm not sure how to
fix it.

Use display: none to hide loading spinners

---

.ruby-style.yml

https://trello.com/c/8plKSKKM
See https://github.com/bbatsov/rubocop/issues/1633

Fix rules for indenting multiline assignments

---

app/models/repo_config.rb
spec/models/repo_config_spec.rb

The value can be a single entry:
inherit_from: .rubocop_todo.yml
which will be parsed as just a string.
This change ensures we are always dealing with an array.

Convert inherit_from value to array

---

app/controllers/build_workers_controller.rb
app/workers/language_worker/scss.rb
app/workers/language_worker/style_guide_worker.rb
spec/controllers/build_workers_controller_spec.rb
spec/spec_helper.rb
spec/support/helpers/api_helper.rb
spec/support/shared/language_not_moved_to_iron_worker.rb
spec/workers/language_worker/scss_spec.rb

We are going to send a token with payload to workers and workers will be sending back that token in headers so we can verify calls.

Prevent hound builld_workers call with a secret token 

---

.ruby-style.yml

@gylaz, this should work, right?

Exclude spec directory when checking for long methods

---

app/models/style_guide/ruby.rb
spec/models/style_guide/ruby_spec.rb

We call `make_excludes_absolute` on the configuration
to satisfy RuboCop's `file_to_exclude?` since it calls `File.expand_path`
on the filename that we pass it.
Thus, all of our `Exclude` paths for individual cops get expanded to absolute as
well. We need to call `File.expand_path` on the filename in order for the two
paths to match.
This is kind of silly, since GitHub does not give us absolute paths, so we
should be fine with just the relative paths (relative to project root),
because they would match what the user puts in their config.
Basically, all of this (plus `make_excludes_absolute`) is because of
`file_to_exclude?`.

Use absolute file paths to fix excluding

---

app/controllers/repos_controller.rb
app/jobs/retryable.rb
app/models/pull_request.rb
app/models/user.rb
app/services/build_runner.rb
config/environments/test.rb
db/migrate/20150306184045_add_token_to_users.rb
db/schema.rb
lib/github_api.rb
spec/models/pull_request_spec.rb
spec/services/build_runner_spec.rb
spec/spec_helper.rb

* Use user's token for PR fetching content, fetching comments, and setting status
* Use Hound's token for commenting and accepting org invites
* Save user's token if he doesn't have one upon viewing repos
Remaining changes?

Use inidividual tokens for as much as possible

---

doc/SECURITY.md

We are now storing GitHub tokens in Postgres, so this update includes that.

Update security document

---

app/models/style_guide/coffee_script.rb
spec/models/style_guide/coffee_script_spec.rb

This PR is a follow up to
https://github.com/thoughtbot/hound/commit/6cec20ad0cb47ce807e631ede531efd3f39ba067
and fixes an issue where the new `coffeescript` would not be picked up.

Set StyleGuide::CoffeeScript#name

---

app/models/violation.rb
app/services/build_runner.rb
config/locales/en.yml
spec/models/violation_spec.rb
spec/services/build_runner_spec.rb
spec/support/helpers/github_api_helper.rb

* Treats multiple messages on a line as separate violations.
* The status message will be overwritten when new commits are pushed to
the PR.
* Updates feature spec stubbing to not care what message is passed.
https://trello.com/c/oCqXJB1V
<hr>
<hr>

Include violation count in GitHub status message

---

app/services/repo_synchronization.rb

This wraps the loop in `RepoSynchronization#start` in a transaction. This way
all the `INSERT`s will happen together or not at all, which should lead to more
consistent repo syncs.

Wrap repo sync inserts in a transaction

---

app/helpers/application_helper.rb

There was an N+1 query firing whern we checked if a `user` has had a previous
`build` (used to determine if we should display onboarding copy).
This change refactors the check to a single query. It may make sense later to
move this query elsewhere entirely.
Fixes
https://trello.com/c/axeF15jZ/566-investigate-n-1-query-on-builds-in-web-process

Refactor display_onboarding? query

---

app/services/repo_subscriber.rb
spec/services/repo_subscriber_spec.rb

We've recently encountered a situation where we believe the customer had
a subscription, but was attempting to activate again -- this can also be
caused by duplicate, simultaneous requests for the same user.
There is not reason to not return the existing subscription, if it
exists and avoid charging the user again via Stripe.

Return an existing subscription during activation

---

app/models/style_checker.rb
app/models/style_guide/coffee_script.rb
spec/models/style_checker_spec.rb
spec/models/style_guide/coffee_script_spec.rb

To avoid eval-ing `erb` tags, due to security reasons, we could instead
replace it the tag with a dummy value. I picked an emtpy string since
that seemed the easier way of solving it.
Thoughts?

Lint `coffee.erb`

---

app/models/commit_file.rb
app/models/pull_request.rb
app/models/style_checker.rb
spec/models/commit_file_spec.rb
spec/models/pull_request_spec.rb
spec/models/style_checker_spec.rb

`PullRequest#pull_request_files` now only returns the *current* files of a pull request. Previously it would return files that had been removed, and left the responsibility of not operating on them up to other parts of the application.
This is the first step in an attempt to split up #727 into smaller chunks that can be reviewed more thoroughly. I started with this small change so I could get people's thoughts on this approach to try to determine if splitting it up is worth pursuing.

Only return current pull request files

---

app/models/build.rb
app/models/file_review.rb
db/migrate/20150425204143_create_file_reviews.rb
db/schema.rb
spec/factories.rb
spec/models/build_spec.rb
spec/models/file_review_spec.rb

This model will represent the progress of a file review, particularly those done by an external system, e.g. IronWorker.
This is another extraction of a small chunk of functionality from #727. It went under the name `BuildWorker` in that PR.

Introduce FileReview model

---

app/models/style_guide/scss.rb
spec/models/style_guide/scss_spec.rb

Users can provide excludes for SCSS linters as an array:
exclude:
- lib/**
- spec/assets/**
or as a string:
exclude: spec/assets/**
We need to run the config hash through SCSSLint's methods to normalize
all of the options. In order to do that, we need to write to a file and
provide a path to that file.
Related error: https://app.getsentry.com/hound-1/production/group/63380345/

Handle single (non-array) SCSS excludes

---

Gemfile.lock
app/services/build_report.rb
app/services/build_runner.rb
spec/services/build_report_spec.rb
spec/services/build_runner_spec.rb

`BuildReportJob` should stand in place of the GitHub interactions in
`Review` in #727 with the plan of using it in the build workers
controller. Also change `Commenter` to accept a `Payload` and create its
own `PullRequest` instance.
Up next will be implementing the `BuildWorkers` controller
that will check for build completion, persist violations, and enqueue
this job.
https://trello.com/c/CdExHIVN

Extract build finalization to job

---

app/services/build_runner.rb
spec/factories.rb
spec/services/build_runner_spec.rb
spec/services/repo_subscriber_spec.rb

When a repo cannot be reached with a user's token,
causing a 404 Not Found error,
that means that user has been barred access to it.
By removing the repo from user's associated repos,
the job will be retried with a different user's token,
or fallback to Hound's.
This should fix numerous 404 errors that are causing jobs to fail.

Remove unreachable repo from user's repos

---

app/controllers/accounts_controller.rb
app/models/payment_gateway_customer.rb
app/presenters/account_page.rb
config/routes.rb
spec/controllers/accounts_spec.rb
spec/features/account_spec.rb
spec/models/payment_gateway_customer_spec.rb
spec/support/helpers/stripe_api_helper.rb

* Support updating an account's billable email address
* Introduce `PATCH /account` endpoint
* Add `PaymentGatewayCustomer#update_email`
* Add `AccountPage#billable_email` and returns billable email in `GET
/account` response

Add API endpoint for updating account

---

app/models/style_guide/base.rb
app/models/style_guide/coffee_script.rb
app/models/style_guide/haml.rb
app/models/style_guide/ruby.rb
app/models/style_guide/scss.rb
app/models/style_guide/unsupported.rb
spec/models/style_guide/haml_spec.rb
spec/models/style_guide/ruby_spec.rb
spec/models/style_guide/scss_spec.rb
spec/models/style_guide/test_spec.rb
spec/models/style_guide/unsupported_spec.rb

We noticed that new file review records are being created without `completed_at` values. This should avoid that and not save any file reviews without `completed_at`.

Always save completed file reviews

---

app/helpers/analytics_helper.rb
app/views/application/_analytics.haml
app/views/application/_auth_button.haml
spec/helpers/analytics_helper_spec.rb

* Listen for link clinks on all `auth` elements on the page,
not just the first one in the header.
* Don't add `trackClick` listener for each
`_auth_button` partial render.
Refactoring:
* Remove unnecessary `ANALYTICS` environment variable.
This is in line with our other apps.

Listen for link clicks correctly

---

spec/features/repo_list_spec.rb

Having this value hard coded led to hard to debug failures
when your local `HOUND_GITHUB_USERNAME` was not "houndci".
This was because the `WebMock` stubs were stubbing
with "houndci" and the app makes requests
based on the `ENV` var.

Use ENV var instead of fixed value in repo_list_spec

---

app/controllers/sessions_controller.rb
db/migrate/20150612231322_add_utm_source_to_users.rb
db/schema.rb

The goal of this change is to make it easier
to query the customer acquisition channel
where the user came from.

Store utm_source on user

---

app/models/payment_gateway_customer.rb
app/models/payment_gateway_subscription.rb
app/services/update_stripe_metadata.rb
spec/models/payment_gateway_subscription_spec.rb
spec/services/repo_subscriber_spec.rb
spec/support/helpers/stripe_api_helper.rb

Stripe metadata does not support arrays.
The metadata must be a string.
Fixes these errors from Stripe:
{
error:
{
type: "invalid_request_error"
message: "Invalid val: ["161936", "326736"] must be a string under 500 characters"
param: "metadata"
}
}

Save subscription metadata as string

---

app/models/style_guide/scss.rb
lib/ext/scss-lint/config.rb
spec/models/style_guide/scss_spec.rb

Monkey patch the SCSSLint gem to expand the file path
to the same directory as the config file.
Since the config file is a Tempfile,
that directory can be acquired by creating another Tempfile
This only makes the top level `exclude:` option work
in the SCSSLint configuration file.
`exclude` at each individual SCSS linters level will not work
because we are passing SCSSLint string (file content),
and thus file path is not available when SCSSLint needs it.

Add ability to exclude SCSS files

---

app/models/style_guide/scss.rb

Since `lib/` is being auto-loaded, we don't need to specify it.

Fix load path of the scss-lint patch

---

spec/services/build_runner_spec.rb

There are intermittent test failures,
due to us setting the `github_id` on repo.
Since the repo factory sets the `github_id` via sequence,
sometimes there are conflicts with what we set.
No tests depend on explicit `github_id`, so this commit kills it.

Fix intermittent test failures

---

app/models/repo_config.rb
spec/models/repo_config_spec.rb

This change allows users to configure Haml style and fixed `KeyError: key not found: "haml"`.

Support Haml configuration

---

app/jobs/completed_file_review_job.rb
spec/jobs/completed_file_review_job_spec.rb

I believe there are cases where a SCSS review can finish before the build is saved. This change handles that case by rescheduling the `CompletedFileReview` job when the build doesn't exist.

Reschedule job if build hasn't been created yet

---

app/jobs/completed_file_review_job.rb
spec/jobs/completed_file_review_job_spec.rb

This is recommended by Heroku and is necessary since we aren't extending `ApplicationJob`. We aren't extending `ApplicationJob` because the style review services serialize jobs using the job class, not `ActiveJob`s wrapper class.

Handle Resque::TermException in CompletedReviewJob

---

config/style_guides/ruby.yml
config/style_guides/thoughtbot/ruby.yml

Using [Predicate matchers][predicates] is a common convention
within the RSpec community.
[Related blog post][blog-post].
[predicates]: https://www.relishapp.com/rspec/rspec-expectations/v/3-2/docs/built-in-matchers/predicate-matchers
[blog-post]: http://www.elabs.se/blog/51-simple-tricks-to-clean-up-your-capybara-tests

Exclude predicate matcher rule for RSpec specs

---

app/views/accounts/show.haml

* Only show the form for updating the billable email on an account if the
current user has a Stripe customer ID. Users who aren't in Stripe's
system shouldn't have the ability to update their billable email
address.

Show email update form if user is Stripe customer

---

app/jobs/completed_file_review_job.rb
app/models/commit_file.rb
app/models/pull_request.rb
app/models/style_checker.rb
app/models/style_guide/coffee_script.rb
app/models/style_guide/haml.rb
app/models/style_guide/java_script.rb
app/models/style_guide/ruby.rb
app/models/style_guide/scss.rb
app/models/style_guide/unsupported.rb
spec/jobs/completed_file_review_job_spec.rb
spec/models/commit_file_spec.rb
spec/models/patch_spec.rb
spec/models/pull_request_spec.rb
spec/models/style_checker_spec.rb
spec/models/style_guide/java_script_spec.rb
spec/models/style_guide/scss_spec.rb
spec/services/build_report_spec.rb
spec/services/build_runner_spec.rb

* Fixes an issue where multiple builds could be created with the same `commit_sha` and the correct one might not be found in `CompletedFileReview`.
* Makes it easier to use `CommitFile`, it lets you initialize `CommitFile` without having to create `file` and `commit` objects
* Gets rid of an `OpenStruct` in `CompletedFileReview`
* Makes it clear what type of "file" object we are dealing with. `CommitFile` was often confused with what returned by `GithubApi` and `Octokit` when fetching pull request files
* Avoids confusing `patch_body` and `patch`

Refactor CommitFile

---

app/helpers/configuration_helper.rb

SCSS config now lives in the worker, so we should point there.

Point to new SCSS config location

---

app/models/repo.rb
spec/models/repo_spec.rb

There are situations when both github_id and github_name are taken
by other repos. We don't want to fail the sync in that case,
but we do want to get notified, and address those repos manually.

Don't hard-fail on repo update during sync

---

app/services/build_report.rb
spec/services/build_report_spec.rb

This will allow us to respect the MAX_COMMENTS environment variable
across the whole build and should help alleviate some abuse warnings.
As-is, if an external worker fails for whatever reason, the build will
not be marked as complete and comments will never go out. I *think*
we'll want to get that working by having the workers be retryable and we
can mark the build as complete if it fails too many times. Maybe this is
good enough for now, though?

Don't comment until the build is finished

---

.env
.gitignore
bin/setup
circle.yml

Moves .sample.env to .env. This file has all the config necessary to get
running in development and `cp .sample.env .env` was in `bin/setup`. If
this file just exists as `.env` in the repo, then the setup step is not
needed and things should Just Work™ out of the box. The dotenv [docs][1]
even recommend doing this to ease new developers onto the project.
Additionally, our heavy use of `ENV.fetch` is now causing the test suite
to [fail][2] on CircleCI, because the database is being setup before the
`pre` hook fires. With `.env` the test suite will work fine without this
setup.
Local customizations can be added to `.env.local`, which is ignored.
[1]: https://github.com/bkeepers/dotenv#should-i-commit-my-env-file
[2]: https://circleci.com/gh/thoughtbot/hound/202

Include .env in the repo

---

app/jobs/completed_file_review_job.rb
app/models/build.rb
app/models/commit_status.rb
app/services/build_report.rb
app/services/build_runner.rb
config/initializers/constants.rb
db/migrate/20150710220040_associate_user_to_build.rb
db/schema.rb
spec/factories.rb
spec/jobs/completed_file_review_job_spec.rb
spec/models/build_spec.rb
spec/services/build_report_spec.rb
spec/services/build_runner_spec.rb

This solves the issue where the app was always setting
the final success status with `houndci`'s token,
instead of user's token (if available).
This also gets all that code out of `BuildRunner`
and into its own `CommitStatus` class.

Extract PR status setting to CommitStatus class

---

app/jobs/go_review_job.rb
app/models/repo_config.rb
app/models/style_checker.rb
app/models/style_guide/go.rb
app/views/pages/configuration.haml
doc/SECURITY.md
spec/models/repo_config_spec.rb
spec/models/style_guide/coffee_script_spec.rb
spec/models/style_guide/go_spec.rb
spec/models/style_guide/haml_spec.rb
spec/models/style_guide/java_script_spec.rb
spec/models/style_guide/ruby_spec.rb
spec/models/style_guide/scss_spec.rb
spec/rails_helper.rb
spec/support/helpers/commit_file_helper.rb

This adds basic support to Hound for Go,
by integrating against [hound-go]
via Hound's external review Resque API.
This should be considered an early release feature.
As the review service matures
and the feature-set stabilizes,
we can define supported configuration options
and the necessary documentation
to promote this to an officially supported language.
[hound-go]: github.com/thoughtbot/hound-go

Add Go as a new language supported by Hound.

---

app/assets/javascripts/directives/repo.js.coffee.erb
app/assets/javascripts/directives/repo_list.js.coffee.erb

* Users without a credit card on file are currently unable to activate
paid repos when using Safari on an iOS device: When the user attempts
to activate a private repo in her repo list by clicking the "Activate"
button, the Stripe Checkout popup does not appear and the user is
unable to proceed with the transaction.
This is because the trigger for displaying the popup is currently
invoked in a callback. Per Stripe's documentation, this implementation
causes "mobile devices and some version of Internet Explorer [to]
block the popup and prevent users from checking out". Reference:
https://stripe.com/docs/checkout#integration-more-runloop
* This commit changes the `Repo` and `RepoList` scripts to load user
payment information earlier in the run loop, thereby allowing us to
decouple fetching …

Ensure checkout modal can be displayed

---

.hound.yml
app/models/commit_status.rb
app/models/repo_config.rb
app/services/build_report.rb
app/services/build_runner.rb
config/locales/en.yml
spec/models/repo_config_spec.rb
spec/services/build_report_spec.rb
spec/services/build_runner_spec.rb

Adds a configuration option to set the PR status to 'error' when
violations are found.
*.hound.yml*
```yaml
fail_on_violations: true
```
https://trello.com/c/MtnDjmfF

Add option to fail the build

---

app/models/commit_status.rb
app/models/repo_config.rb
app/models/repo_config/parser_error.rb
app/services/build_runner.rb
config/locales/en.yml
spec/models/repo_config_spec.rb
spec/services/build_runner_spec.rb

Adds a `filename` field to the `RepoConfig::ParserError` exception class
and uses it when setting the GitHub status.
https://trello.com/c/vCW2P0eX

Include filename in config parse error

---

app/models/repo_config.rb
app/views/pages/configuration.haml
config/style_guides/haml.yml
spec/models/repo_config_spec.rb
spec/models/style_guide/haml_spec.rb

* Now that we have `BETA_LANGUAGES`, thanks @bernerdschaefer, we don't have to disable all rules in config to disable Haml review.
* If you want Haml review you will need to enable it in `.hound.yml`.

Consider Haml review as beta

---

db/migrate/20150731212842_remove_repo_limit_constraint_on_bulk_customers.rb
db/schema.rb

Why:
* Some customers, like thoughtbot, may not have a limit.

Remove repo_limit null constraint on bulk_customers

---

config/database.yml

Why:
* `DATABASE_URL` only needs to be defined in production environment
* Raises an error if not set in dev/test environments

Only fetch DATABASE_URL in production env

---

app/services/build_runner.rb
spec/services/build_runner_spec.rb

Why:
* There is currently a problem where reviews have been schedules
but the assosiated build cannot be found.
* Possibly the build creation failed for some reason,
but, as is, the review jobs get scheduled anyways.

Ensure build exists before scheduling reviews

---

config/newrelic.yml

This should make our request time charts more realistic.

Configure New Relic to ignore /assets

---

app/controllers/activations_controller.rb
app/controllers/application_controller.rb
app/controllers/deactivations_controller.rb
app/controllers/repo_syncs_controller.rb
app/controllers/repos_controller.rb
app/controllers/sessions_controller.rb
app/controllers/subscriptions_controller.rb
app/jobs/repo_synchronization_job.rb
app/services/repo_synchronization.rb
spec/controllers/activations_controller_spec.rb
spec/controllers/deactivations_controller_spec.rb
spec/controllers/repo_syncs_controller_spec.rb
spec/controllers/subscriptions_controller_spec.rb
spec/features/repo_list_spec.rb
spec/features/user_authentication_spec.rb
spec/jobs/repo_synchronization_job_spec.rb
spec/services/repo_synchronization_spec.rb
spec/support/helpers/authentication_helper.rb

This change updates the user's token each time they sign in. The token used to be saved once, when the token in the database was null, and never updated again.
This change also requires a token be saved in the database and will redirect to the landing page if token is null. We used to allow users to sign in without saving a token to prevent currently authenticated users from going back through the auth flow.
This also sets us up for having two levels of access in Hound since we are updating the token during auth flow.

Update and use token in database when creating a session

---

app/views/pages/configuration.haml

It should be clear how to disable Haml since it's disabled by default and we show instructions for enabling.

Remove unnecessary Haml docs

---

app/jobs/accept_org_invitations_job.rb
app/jobs/completed_file_review_job.rb
app/models/pull_request.rb
lib/big_brother.rb
spec/jobs/completed_file_review_job_spec.rb
spec/lib/github_api_spec.rb
spec/support/helpers/github_api_helper.rb

As we have this constant which we can use everywhere in code so we don't need to use `.fetch` on ENV

Use Hound::GITHUB_TOKEN constant everywhere

---

app/assets/javascripts/directives/repo_list.js.coffee.erb
app/assets/stylesheets/repos/_index.scss
app/controllers/sessions_controller.rb
app/models/github_auth_options.rb
app/models/user.rb
app/views/application/_header.haml
app/views/templates/repo_list.haml
config/initializers/omni_auth.rb
config/locales/en.yml
db/migrate/20150728154011_add_token_scopes_to_users.rb
db/schema.rb
lib/github_api.rb
spec/controllers/sessions_controller_spec.rb
spec/features/repo_list_spec.rb
spec/lib/github_api_spec.rb
spec/models/github_auth_options_spec.rb
spec/support/helpers/authentication_helper.rb
spec/support/helpers/github_api_helper.rb

Addresses https://github.com/thoughtbot/hound/issues/597 and https://github.com/thoughtbot/hound/issues/701.

Allow users to try Hound without giving access to private repos

---

app/controllers/builds_controller.rb

As this has been removed in aaef09bb2ee10d5d7370ce62b77c93063bafa626

Remove force_https? from BuildsController

---

config/application.rb
config/initializers/cookies_serializer.rb
config/initializers/filter_parameter_logging.rb

This reverts commit 9988a31724e61a7a4363bc582bc7ef776e91d428.
Changing cookie serialization to JSON causes the app to fail when attempting to parse old cookies that aren't JSON. See also: #892

Revert "Structure files according to used version of rails"

---

app/controllers/application_controller.rb
app/controllers/builds_controller.rb
app/services/repo_activator.rb
config/application.rb
config/environments/production.rb
config/environments/staging.rb
spec/controllers/application_controller_spec.rb
spec/support/helpers/https_helper.rb

Reverts aaef09bb2ee10d5d7370ce62b77c93063bafa626 and 3b22d42c1ded47a485e2f8bf6bc9e6138784aa58.
The SSL refactorings were forcing all incoming traffic to use `https`, but we have old webhooks in the wild that still use `http`. GitHub's webhooks do not honor redirects, so those payloads will fail and users will not have their PRs reviews.

Revert SSL refactoring

---

app/jobs/swift_review_job.rb
app/models/repo_config.rb
app/models/style_checker.rb
app/models/style_guide/swift.rb
spec/models/repo_config_spec.rb
spec/models/style_guide/swift_spec.rb

Why:
* Requested by Users
* We want to use it internally :)
This change addresses the need by:
* Adding Swift support so that Hound queues jobs for Swift
that the worker can pick up.
Swift Service Repo: https://github.com/thoughtbot/hound-swift

Add Swift Support

---

.env
Gemfile
Gemfile.lock
app/controllers/admin/application_controller.rb
app/dashboards/bulk_customer_dashboard.rb
app/dashboards/dashboard_manifest.rb
app/models/bulk_customer.rb
config/routes.rb
spec/features/admin_authorization_spec.rb

- Admin handles can be set through an environment variable, `ADMIN_GITHUB_USERNAMES`.
See individual commit messages for more detailed descriptions of changes

Add an admin dashboard through Administrate

---

app/views/home/index.haml

Hopefully this makes pricing more clear. We've had questions about whether Hound subscription is for a single private repo or all private repos.
before:
after:

Change pricing description

---

app/views/application/_header.haml

> Go to houndci.com, click on docs or FAQ link at the top, then click pricing link at the top. The #pricing gets added to the URL but that doesn't go anywhere unless you're on the initial houndci.com URL.

Fix pricing link

---

app/assets/javascripts/directives/repo_list.js.coffee.erb
app/assets/stylesheets/repos/_index.scss
app/controllers/sessions_controller.rb
app/models/github_auth_options.rb
app/models/user.rb
app/services/repo_activator.rb
app/views/application/_header.haml
app/views/templates/repo_list.haml
config/initializers/omni_auth.rb
config/locales/en.yml
db/migrate/20150728154011_add_token_scopes_to_users.rb
db/schema.rb
lib/github_api.rb
spec/controllers/sessions_controller_spec.rb
spec/features/repo_list_spec.rb
spec/lib/github_api_spec.rb
spec/models/github_auth_options_spec.rb
spec/models/user_spec.rb
spec/services/repo_activator_spec.rb
spec/support/helpers/authentication_helper.rb
spec/support/helpers/github_api_helper.rb

Addresses https://github.com/thoughtbot/hound/issues/597 and https://github.com/thoughtbot/hound/issues/701.
The first time around we were missing `public_repo`. This change includes that scope and the original work.
Here are some screen shots taken during testing:

Reduce GitHub access necessary to start using Hound

---

config/initializers/omni_auth.rb
config/initializers/sentry.rb

The default is STDOUT, which is inconsistent with other logs and was
filling test output with irrelevant messages.

Configure OmniAuth to use Rail's logger

---

app/jobs/completed_file_review_job.rb
app/models/style_checker.rb
app/models/style_guide/base.rb
app/models/style_guide/coffee_script.rb
app/models/style_guide/go.rb
app/models/style_guide/haml.rb
app/models/style_guide/java_script.rb
app/models/style_guide/python.rb
app/models/style_guide/ruby.rb
app/models/style_guide/scss.rb
app/models/style_guide/swift.rb
app/services/build_runner.rb
spec/models/style_checker_spec.rb
spec/models/style_guide/coffee_script_spec.rb
spec/models/style_guide/go_spec.rb
spec/models/style_guide/haml_spec.rb
spec/models/style_guide/java_script_spec.rb
spec/models/style_guide/python_spec.rb
spec/models/style_guide/ruby_spec.rb
spec/models/style_guide/scss_spec.rb
spec/models/style_guide/swift_spec.rb
spec/models/style_guide/test_spec.rb
spec/models/style_guide/unsupported_spec.rb
spec/services/build_runner_spec.rb

Why:
* SCSS worker is very fast and sometimes performs a review before the
build and file reviews are saved.
This will case the complete job to fail, since it won't find the
file review.
Addresses: https://app.getsentry.com/hound-1/production/group/70334013

Save file reviews before queueing a review job

---

app/models/style_guide/base.rb
app/models/style_guide/go.rb
app/models/style_guide/scss.rb
app/models/style_guide/swift.rb

Why:
* All service-based style guides enqueue almost identical jobs.
* We can derive what is different from the class itself.
* Less code to add when we add more service-based linters.

Extract duplicate file_review method into Base

---

bin/setup

Why:
* We use `.env.local` file to override env vars from `.env`.

Add foreman support for .env.local

---

app/jobs/completed_file_review_job.rb
app/models/commit_file.rb
app/models/pull_request.rb
app/models/style_guide/base.rb
app/models/style_guide/python.rb
spec/models/commit_file_spec.rb
spec/models/style_checker_spec.rb
spec/models/style_guide/go_spec.rb
spec/models/style_guide/python_spec.rb
spec/models/style_guide/scss_spec.rb
spec/models/style_guide/swift_spec.rb
spec/support/helpers/style_guide_helper.rb

Why:
* We were fetching content for all changed files,
even ones that we won't review because of their unsupported extension.
* Because of this we were wasting API requests on such files.
* There was an issue where a file was named `[:facebook]`
and we tried to fetch its content.
Because, by GitHub's design, file path is part of th URL,
it was raising an error, because that is not a valid URL

Fetch file contents when file is being reviewed

---

config/style_guides/thoughtbot/coffeescript.json
spec/models/style_guide/coffee_script_spec.rb

Oftentimes it's useful in tests to stub out methods on objects with
empty functions.
For instance you might make a helper function in a test file:
``` coffee
buildSomeFakeObject = (overrides = {}) ->
_.defaults overrides,
foo: ->
bar: ->
```
and then later on in the test, you might say:
``` coffee
fakeObject = buildSomeFakeObject()
spyOn(fakeObject, "foo")
...
expect(fakeObject.foo).toHaveBeenCalled()
```
Currently, Hound will complain within `buildSomeFakeObject` that `foo`
and `bar` are empty functions. This creates a lot of noise.
I don't think this rule is necessary in the general case anyway -- I've
never seen anyone make an empty function accidentally.

CoffeeScript: Remove 'Empty function' violation

---

spec/models/style_checker_spec.rb

Why:
* Because fitting such changes into PRs when we touch them generates
a lot of noise, and thus doing them separately is an easier task.

Format style checker spec to conform to our guides

---

app/jobs/markdown_review_job.rb
app/models/repo_config.rb
app/models/style_checker.rb
app/models/style_guide/markdown.rb
spec/models/repo_config_spec.rb
spec/models/style_checker_spec.rb
spec/models/style_guide/markdown_spec.rb

Why:
* Reviewing Markdown for style violations is neat.
* We should support well-know Markdown file extensions.
https://trello.com/c/mzlQMOCl

Add support for Markdown service

---

app/views/pages/configuration.haml

This section is about JavaScript config, remove unnecessary scss config.
See: https://houndci.com/configuration#javascript

Remove unnecessary scss config in JavaScript config section

---

app/models/style_guide/base.rb
app/models/style_guide/python.rb
spec/models/style_guide/python_spec.rb

* Updates the Python service to be serialized with a hash argument, rather
than an array.
* Adds a `StyleGuide::Base#enqueue_job` private method that handles the
Resqueue details. The Python linter overrides this because it has a
non-standard class name, `review.PythonReviewJob`. As far as I can
tell, this name is required because the Python Resuque library, Pyres,
uses the python import system, which needs a module name. I'd love to
hear more about this from anyone with more knowledge.

Standardize Python service attributes

---

CONTRIBUTING.md

To reflect that those linters are out of beta and restructure the list.
https://github.com/thoughtbot/hound/pull/936

Edit the Go and Haml mentions in CONTRIBUTING.md

---

app/views/pages/configuration.haml

This feature has been in production for awhile and is working well.
Documenting it will allow users to know of its existence, without having
to ask us.
Closes #943

Document failing on violations

---

app/helpers/analytics_helper.rb
app/models/user.rb
spec/helpers/analytics_helper_spec.rb
spec/models/user_spec.rb

Why:
* When providing support via Intercom it saves us a step asking the
customer to provide their repo information.
https://trello.com/c/FOZl9Sg3

Send active repo ids to Intercom to simplify support

---

app/views/home/index.haml

I assume Ruby was first because it was supported first and is still has
the largest percentage of builds. However, with the move towards equal
opportunity linters, it's awkward to have Ruby up front. Sorting
alphabetically seems good to me.
In c0ea6270a5b7aaccc0c8499fa047b7b06836543e, I forgot to create a
feature branch and accidentally pushed to master :frowning: . Since it
doesn't include any breaking changes, I think I don't want to muddy
the history further by introducing a revert commit, then going through
our PR flow. I'm hoping for this one to serve in its place.

Order language logos alphabetically

---

config/style_guides/ruby.yml
spec/models/linter/ruby_spec.rb

This is a move towards removing Hound's defaults and relying on underlying linter libraries for defaults.
The options that will break functionality for a majority of users will be updated after this change and after messaging users about the upcoming change.
Cops that are enabled by this change:
* Style/ClassAndModuleChildren
* Style/CommentAnnotation
* Style/FormatString
* Style/LambdaCall
* Style/Next
* Style/NumericLiterals
* Style/RegexpLiteral
* Style/WhileUntilModifier
* Style/WordArray
* Metrics/BlockNesting
* Rails/ActionFilter
* Style/EvenOdd
* Style/InitialIndentation
* Style/FlipFlop
* Style/IfWithSemicolon
* Style/Lambda
* Style/LineEndConcatenation
* Style/NegatedIf
* Style/NegatedWhile
* Style/Not
* Style/SelfAssignment
* Lint/ConditionPosition
* Lint/ElseLayout
* Lint/Void …

Use RuboCop defaults for most cops

---

app/jobs/buildable.rb
app/models/payload.rb
app/models/repo.rb
app/services/build_runner.rb
app/services/update_repo_status.rb
spec/jobs/buildable_spec.rb
spec/models/payload_spec.rb
spec/models/repo_spec.rb
spec/services/build_runner_spec.rb
spec/services/update_repo_status_spec.rb

The idea is to keep repo attributes updated always so we can track public/private flag change on repo from GitHub.

Update repo attributes on each build

---

.ruby-style.yml
config/style_guides/thoughtbot/ruby.yml

Allow multiline block chaining
For testing that an exception occured, multiline block chaining
might be needed to follow other guides we have.
Example:
```ruby
expect do
Config::Parser.load_yaml(hound_config, "config/rubocop.yml")
end.to raise_error do |exception|
expect(exception).to be_a Config::Parser::Error
expect(exception.message).to eq(
"`config/rubocop.yml` must be a Hash",
)
expect(exception.filename).to eq "config/rubocop.yml"
end
```
- To keep the line under 80 characters, it sometimes can't be re-written
using `{}` instead of `do/end`.
- `{}` shouldn't be used for multiline blocks.
- If you want to assert more things on the exception, you have to yield
a block to `raise_error` to do so.
I propose to relax this rule by allowing to chain blocks that spans
over multiple lines.

Allow multiline block chaining

---

app/models/hound_config.rb
spec/models/config/ruby_spec.rb
spec/models/hound_config_spec.rb
spec/models/linter/base_spec.rb

Linters that are supported[1] out of the box for Hound, should not be
enabled in the users `.hound.yml`[1]
Beta languages still needs to be enabled in the configuration[2]
[1]
```yaml
ruby:
enabled: true
```
[2]
```yaml
python:
enabled: true
```

Allow supported languages to be unconfigured

---

app/models/config/ruby.rb
spec/models/config/ruby_spec.rb

A regression was introduced in fec130b, where Hound didn't
respect the specified files to inherit its configuration from.

Support `inherit_from` from Rubocop

---

app/models/linter/collection.rb
app/models/style_checker.rb
spec/models/linter/collection_spec.rb

`Linter::Collection` wraps a list of linters. To work as a replacement
for a single `Linter`, even though multiple linters are used.

Support multiple linters per file

---

app/jobs/eslint_review_job.rb
app/models/config/eslint.rb
app/models/hound_config.rb
app/models/linter/collection.rb
app/models/linter/eslint.rb
app/models/linter/java_script.rb
spec/models/config/eslint_spec.rb
spec/models/linter/eslint_spec.rb
spec/models/style_checker_spec.rb

Add support for `eslint` backed by `hound-eslint`
Eslint is disabled by default, alongside any other Beta linters.
To enabled it, simplify configure your `.hound.yml`:
```yaml
eslint:
enabled: true
config_file: config/.eslintrc
ignore_file: config/.eslintignore
```
This is backed by [hound-eslint]
[hound-eslint]: https://github.com/thoughtbot/hound-eslint
Changes:
- Implement `Config::Eslint` and `Linter::Eslint`.
- Support `*.js`, `*.es6`, and `*.es6.js`, for file extensions.
- Replace `!collection.any?` with `collection.none?`
https://trello.com/c/2a6yQORa

Add support for `Eslint` alongside `JShint`

---

CONTRIBUTING.md
app/jobs/report_invalid_config_job.rb
app/services/build_runner.rb
spec/jobs/report_invalid_config_job_spec.rb
spec/services/build_runner_spec.rb
spec/services/report_invalid_config_spec.rb

Either by executing the service, `ReportInvalidConfig`. Or by enqueueing
the corresponding job, `ReportInvalidConfigJob`.
https://trello.com/c/42U5K0Bs

Allow services to report config files as invalid

---

app/models/config/ruby.rb
spec/models/config/ruby_spec.rb

This is a behavior Rubocop has, Hound should not be any different.
Changes:
- Refactor: Move `ensure_correct_type` to `Config::MY_CONFIG#content`.
The `#parse` method should not do more than just parsing.
Resolves #983

Don't merge empty Rubocop configurations

---

app/jobs/jscs_review_job.rb
app/models/config/jscs.rb
app/models/hound_config.rb
app/models/linter/collection.rb
app/models/linter/jscs.rb
config/initializers/inflections.rb
spec/models/config/jscs_spec.rb
spec/models/linter/jscs_spec.rb
spec/models/style_checker_spec.rb

Enable JSCS linting by setting the `jscs` config key to `true`.
[hound-jscs]: https://github.com/thoughtbot/hound-jscs/
To enable:
```
jscs:
enabled: true
config_file: .jscsrc
```
https://trello.com/c/M6hL2wKC

Add beta support for JSCS linting via hound-jscs

---

app/jobs/mdast_review_job.rb
app/models/config/mdast.rb
app/models/hound_config.rb
app/models/linter/collection.rb
app/models/linter/mdast.rb
spec/models/config/mdast_spec.rb
spec/models/linter/mdast_spec.rb
spec/models/style_checker_spec.rb

Adds beta support for Markdown linting via [hound-mdast]. under the `mdast` config key.
[hound-mdast]: https://github.com/thoughtbot/hound-mdast/
To enable:
```
mdast:
enabled: true
config_file: .mdastrc
```
https://trello.com/c/9jD9GdL9

Add support for hound-mdast

---

app/models/linter/eslint.rb
app/models/linter/java_script.rb
app/models/linter/jscs.rb
spec/models/linter/eslint_spec.rb
spec/models/linter/java_script_spec.rb
spec/models/linter/jscs_spec.rb
spec/models/style_checker_spec.rb

They should be named `*.js.coffee`

Drop support for `*.coffee.js` files

---

app/helpers/configuration_helper.rb
app/views/pages/configuration.haml

Split from [#979].
Omit the configuration documentation from [#979] so we can test JSCS out
internally before announcing the public beta.
[#979]: https://github.com/thoughtbot/hound/pull/979/files#r43117833

Add HTML Documentation for JSCS

---

app/jobs/jshint_review_job.rb
app/models/config/jshint.rb
app/models/linter/collection.rb
app/models/linter/jshint.rb
spec/models/config/jshint_spec.rb
spec/models/linter/jshint_spec.rb
spec/models/style_checker_spec.rb

Enable JSHint linting backed by [hound-jshint] by setting the `jshint`
config key to `true`.
[hound-jshint]: https://github.com/thoughtbot/hound-jshint/
To enable:
```
jshint:
enabled: true
config_file: .jshintrc
javascript:
enabled: false
```
The current JavaScript linter is already backed by `JSHint`, so to use
the newer version we must disable the old one.
https://trello.com/c/Xk8StXIm

Add beta support for `JSHint` linting via `hound-jshint`

---

app/models/linter/ruby.rb
spec/models/linter/ruby_spec.rb

Rubocop supports [disabling cops with inline comments][inline-disable],
but Hound does not. This is so because Rubocop still reports the
violations internally, then chooses to ignore those that have been
disabled via comment. Hound is not using the parts of Rubocop that do
this, resulting in comments on the violations. Fortunately there is a
`Offense#disabled?` method which returns true for violations disabled
by comments.
Fixes #995
[inline-disable]: https://github.com/bbatsov/rubocop/tree/2195f366bb47d8d8794943c247c00ba55213900b#disabling-cops-within-source-code

Support disabling cops with inline comments

---

Gemfile
Gemfile.lock
app/dashboards/bulk_customer_dashboard.rb

See Administrate's [CHANGELOG].
- Update dashboards to match new API
- Use new field types
[CHANGELOG]: https://github.com/thoughtbot/administrate/blob/master/CHANGELOG.md

Update Administrate to 0.1.0

---

app/models/config/base.rb
app/models/config/python.rb
spec/models/config/python_spec.rb

The Python linter we're using (Flake8) expects a non-JSON configuration format, and passing `{}` to it causes an exception.
Since constants in Ruby aren't inherited in the same way as methods, we need to move the default to a method in order to override it.

Fix default Python config.

---

app/helpers/configuration_helper.rb
app/views/pages/configuration.haml

This can remain open while it's in beta
but I figured I'd open a PR now
since I have the time.
Why:
* Users would like to know how to add Swift to their projects.
This change addresses the need by:
* Adding the Swift section to the configuration page.

Add configuration page docs for Swift

---

app/models/repo.rb
app/models/violation.rb
db/migrate/20151216235118_add_violations_count_to_builds.rb
db/schema.rb
spec/features/account_spec.rb
spec/models/repo_spec.rb
spec/models/violation_spec.rb

We display the number of violations per repo on the account page (for
paid repos). That was causing timeouts, since repos can have many builds
and sql `IN` uses a loop for large arrays.
To speed things up, we can cache the number of violations (messages) per
build.

Cache number of violations per build

---

app/controllers/repos_controller.rb
app/models/user.rb
app/serializers/repo_serializer.rb
app/services/repo_synchronization.rb
app/views/templates/repo.haml
config/locales/en.yml
db/migrate/20151204174817_add_admin_to_memberships.rb
db/schema.rb
lib/github_api.rb
spec/controllers/activations_controller_spec.rb
spec/controllers/deactivations_controller_spec.rb
spec/features/repo_list_spec.rb
spec/lib/github_api_spec.rb
spec/models/user_spec.rb
spec/serializers/repo_serializer_spec.rb
spec/services/repo_synchronization_spec.rb
spec/support/fixtures/github_repos_response_for_jimtom_page2.json

Why:
Users should be able to see the repos they have access to on GitHub,
but cannot activate due to not having enough access (they are not an
admin). We should communicate in the UI that the repo cannot be
activated.
How:
* Store a flag on membership whether a user is an admin of the repo
* Display all of user's repos on the repos list
* Implement `RepoSerializer#admin?` that uses `current_user`.
* Add a message to each repo that cannot be activated stating why.
https://trello.com/c/XVDAV6uf

Display message for repos that can't be activated

---

spec/spec_helper.rb

When we write tests with multiple expects, only the first failure is
reported when the test fails. `aggregate_failures` allows us to see
any or all the failures that happened in a specific test.
https://www.relishapp.com/rspec/rspec-core/docs/expectation-framework-integration/aggregating-failures

View each failure in specs with multiple expects

---

Gemfile.lock

Why:
* We are a few versions behind.
* There is potential bug that was reported by our customer.

Update Coffeelint gem

---

db/migrate/20151204174817_add_admin_to_memberships.rb

All the existing memberships should have admin status, since we only
added memberships if users were admins of the repos.
Thus, we should preserve that state, otherwise all of the current repos
would say that they require admin permissions, until users re-sync.

Set admin flag on existing memberships to true

---

CONTRIBUTING.md
app/jobs/report_invalid_config_job.rb
app/models/commit_status.rb
app/models/config/base.rb
app/models/config/parser_error.rb
app/services/build_runner.rb
app/services/report_invalid_config.rb
config/locales/en.yml
spec/jobs/report_invalid_config_job_spec.rb
spec/models/commit_status_spec.rb
spec/services/build_runner_spec.rb
spec/services/report_invalid_config_spec.rb

Since the services does not have any concept of a configuration files,
but only the contents of them. It makes more sense to report invalid
configuration files per linter basis instead of per file basis.
Instead of Hound reporting the invalid configuration file by saying:
Error parsing config file: config/rubocop.yml...
Hound will instead report:
Error parsing config file for: ruby...
Which means that the linters does not need to know which file they are
parsing.
https://trello.com/c/42U5K0Bs

Report invalid configuration files per linter

---

app/models/linter/ruby.rb
app/services/ruby_config_builder.rb
spec/models/config/ruby_spec.rb
spec/models/style_checker_spec.rb
spec/services/ruby_config_builder_spec.rb

* Introduces `RubyConfigBuilder` to encapsulate merging RuboCop's
defaults, Hound's defaults, and the user's custom config.
This is a precursor for providing an endpoint for users to fetch their
completely merged config file.

Extract RuboCop configuration merging logic

---

app/jobs/completed_file_review_job.rb
app/services/complete_file_review.rb
spec/jobs/completed_file_review_job_spec.rb
spec/services/complete_file_review_spec.rb

To follow the pattern of a job class having a corresponding service
object.

Extract service from `CompletedFileReviewJob`

---

app/models/config/base.rb
app/models/config/coffee_script.rb
app/models/config/java_script.rb

This allows us to configure that a given linter should respond to
multiple names in the `.hound.yml` configuration file.
https://trello.com/c/oHuaCx6b

Allow a linter to respond to many names

---

app/models/linter/ruby.rb

Rubocop expects the absolute path to a filename for it to be excluded

Add absolute filename to get file exclusion working

---

app/models/config/coffee_script.rb
spec/models/config/coffee_script_spec.rb

This allows `.hound.yml` file to specify `coffeescript` or
`coffee_script`.

Make `coffeescript` accessible under all names

---

app/models/linter/jshint.rb
spec/models/linter/jshint_spec.rb
spec/models/style_checker_spec.rb

This was forgotten in the move done in:
https://github.com/thoughtbot/hound/commit/0eef7e727ba44d8765758efb64a3fc1534490ffc
Changes:
- Check for excluded files in `Linter::Jshint` by leveraging
`Config::Jshint#excluded_files`.
- Rename `eslint` to `jshint` in `spec/models/linter/jshint_spec.rb`
- Remove dead-weight test.
Since the JavaScript linter is extracted out into a service, the violations we get back will always be empty, since they haven't been linted yet.

Exclude files for JSHint

---

app/models/linter/ruby.rb
app/services/ruby_config_builder.rb
spec/models/linter/ruby_spec.rb
spec/services/ruby_config_builder_spec.rb

There is some important code that is run in
`RuboCop::ConfigLoader.merge_with_defaults` -- it checks for presence of
`DisabledByDefault` and disables all of the rules but the overrides.
Because we were calling `RuboCop::ConfigLoader.configuration_from_file`
first (and it calls `merge_with_defaults` in turn) and then merging the
custom config, we were not preserving the `DisabledByDefault` logic.
Fixes #1049

Merge RuboCop overrides first

---

spec/models/config_builder_spec.rb

This test/code doesn't need the whole Rails framework.
Shave off precious time on focused spec runs :)

Reduce spec dependencies for ConfigBuilder

---

app/models/linter/haml.rb
spec/models/linter/haml_spec.rb
spec/support/helpers/commit_file_helper.rb

HamlLint includes the line number in the exception when it encounters an
invalid Haml format. However, the line number is of the line before the
error, thus we need to add one to comment under the erroneous line in
the pull request.

Report invalid HAML format as violation

---

app/models/linter/haml.rb
spec/models/linter/haml_spec.rb

When we pass a filename to HamlLint and RuboCop linter is enabled then
HamlLint will try to create a Tempfile in the directory that it gets
from the file's path. It won't exist on Heroku, so it throws an
exception.
HamlLint still works without a filename, so let's not pass it in.
Fixes the following issue we've been seeing:
```
No such file or directory @ rb_sysopen - app/views/articles/_form.html.haml.haml_lint.tmp20160205-6932-alnw3e
```

Don't pass filename to HamlLint

---

config/style_guides/thoughtbot/ruby.yml

Disable Abc RuboCop rule for thoughtbot

---

CONTRIBUTING.md
app/jobs/mdast_review_job.rb
app/jobs/remark_review_job.rb
app/models/config/remark.rb
app/models/hound_config.rb
app/models/linter/collection.rb
app/models/linter/remark.rb
spec/models/config/remark_spec.rb
spec/models/linter/remark_spec.rb

The hound service is being updated to use `remark`, which is `mdast`'s new name, in https://github.com/thoughtbot/hound-mdast/pull/7. This change brings _that_ name change into Hound so everything is consistent.
https://trello.com/c/vFLTg8IQ

Update for the mdast -> remark rename

---

CONTRIBUTING.md
README.md
app/helpers/configuration_helper.rb
app/views/application/_footer.haml
app/views/errors/500.haml
app/views/home/index.haml
app/views/pages/faq.html.haml
doc/PRIVACY.md
doc/SECURITY.md
spec/models/commit_status_spec.rb
spec/models/repo_spec.rb
spec/services/report_invalid_config_spec.rb
spec/support/fixtures/config_contents.json
spec/support/fixtures/contents.json
spec/support/fixtures/contents_with_violations.json
spec/support/fixtures/pull_request_comments.json
spec/support/fixtures/pull_request_files.json

* `thoughtbot` -> `houndci` rename.
* Take into accoun the `hound-` prefix removal.

Update links to point to the new organization

---

app/views/pages/configuration.haml

I tried the existing example for #scss exclusion, and it doesn't seem to work. If I remove the `scss:` line in the `.scss-style.yml` file, it does work. Cross-confirmed with an example in the linter documentation:
https://github.com/brigade/scss-lint#configuration
Discussion and :+1: in this thread: https://github.com/houndci/hound/issues/1018#issuecomment-186394304
Please merge accordingly if things look good. Cheers!

Update configuration.haml for #scss exclude example

---

app/models/config/base.rb
app/models/config/coffee_script.rb
app/models/config/haml.rb
app/models/config/python.rb
app/models/config/ruby.rb
spec/models/config/base_spec.rb
spec/models/config/haml_spec.rb
spec/models/config/python_spec.rb
spec/models/config/ruby_spec.rb
spec/models/style_checker_spec.rb

We were getting errors because we weren't handling potential errors from
parsing the `inherit_from` files.
Restructure code to make it harder to make this mistake in the future.

Rescue parse error of inherited RuboCop configs

---

app/controllers/repos_controller.rb
app/controllers/subscriptions_controller.rb
app/queries/repos_with_membership_or_subscription_query.rb
app/serializers/repo_serializer.rb
app/services/repo_activator.rb
spec/features/user_deactivates_a_repo_spec.rb
spec/queries/repos_with_membership_or_subscription_query_spec.rb
spec/serializers/repo_serializer_spec.rb
spec/services/repo_activator_spec.rb

If a user has activated a private repo then loses access to it on
GitHub, they cannot deactivate the repo in Hound and Hound continues to
charge their credit card. This change includes repos in this state in
the user's repo list, so they can deactivate it.
* Adds the `OrphanedAndMembershipReposQuery` query object, which
returns repos that a user has a membership and/or subscription for.
* Updates the repo list to include repos that have a subscription but not
a membership.
* Updates `RepoSubscriber#unsubscribe` to only remove the Hound user
and webhook if the user has a membership for that repo (meaning they
have access (probably)).
https://trello.com/c/cb3EUNVC

Allow users to cancel orphaned, private repos

---

bin/production-status

The goal is to get a bird's eye view of what needs to be deployed to
production.
The script assumes all of the hound related repositories are in the same
directory as the main one (this one). It loops over them and attempts to
compare production/master to origin/master, showing the results.

Add script to show what isn't on production

---

app/models/config/eslint.rb
app/models/config/json_with_comments.rb
spec/models/config/eslint_spec.rb
spec/models/config/json_with_comments_spec.rb

ESLint supports a custom JSON format that allows comments.
Neither Ruby's YAML nor JSON can parse that, so we need to remove the
comments before we attempt parsing.
The algorithm was borrowed from
`https://github.com/sindresorhus/strip-json-comments`, which is what
ESLint leverages. [Source](https://github.com/sindresorhus/strip-json-comments/blob/dcc8c7e399ce9ecf4b96aa277a732033fe9dc83a/index.js)

Remove comments from ESLint config file

---

config/style_guides/thoughtbot/ruby.yml

Splitting continuous line at the operator, causes Hound to find a
violation. RuboCop's default is to align the operators, but we want the
next line to be indented one extra level.

Configure operator indentation for thoughtbot

---

lib/github_api.rb
spec/lib/github_api_spec.rb
spec/support/helpers/github_api_helper.rb

Introduced in e9836eea64baefb0699952c5f35fd65a9ca2df41, the logic was in
regard to adding Hound user to teams. Since, we are not doing that
anymore this is not longer relevant to the original problem.
Currently, there is an issue where we choose a user token to handle the
repo, since a repo could be public, the user's token will work for
processing the build/review.
But, it will fail silently when it tries to set the status. This is the
cause of the GitHub status sometimes not being set, a token that was
picked does not have status setting privileges.
If we raise, the pending status will fail and the job will retry using a
new token.

Don't rescue Octokit::NotFound when setting status

---

app/models/config/eslint.rb

`default_content` should be a string, which it is in `Base`.

Remove incorrect default content for ESLint

---

app/models/repo.rb
app/models/user_token.rb
app/services/build_runner.rb
app/services/report_invalid_config.rb
spec/models/user_token_spec.rb
spec/services/build_runner_spec.rb

* Get that concern out of BuildRunner.
* The plan is to use the new `GithubRepo` class in other places.
* We should never encounter `Octokit::Unauthorized` during builds,
because this is the error that is only thrown when someone tries to
authenticate.

Extract GitHub token finding into own class

---

config/style_guides/.jshintignore

`node_modules/` is equivalent to a `vendor/` folder, so it should be ignored by default when running JSHint.

ignore NPM packages from JavaScript linting

---

config/environments/production.rb

At some point, Rails changed the default log level when generating a new
app to `debug`. When we upgraded to that version, we started [seeing
warnings][1] about the missing config value, so we went with `debug` to
match the default.
This has resulted in our production logs being filled with SQL queries
that are not useful to us there, making it difficult to find other
information and exhausting our Papertrail quota.
This changes the production log level to `info`, to cut down on our log
size.
[1]: https://github.com/houndci/hound/commit/5e0aedf4feb28daafdb272178861a259b642d301

Use info log level in production

---

.ruby-style.yml
app/models/linter/eslint.rb
app/models/linter/jshint.rb
lib/js_ignore.rb
spec/lib/js_ignore_spec.rb

There was a bug where `JsIgnore` looked up the ignore file only for the
`javascript` linter. It now takes in a linter name and uses that as the
key to look up in `.hound.yml`.

Lookup ignore files using the linter's name

---

.ruby-style.yml

Looks like the names of the rubocops have changed when hound recently updated, this caused failing PRs.

Updating Rubocop Rule Names

---

app/models/config/jscs.rb
spec/models/config/jscs_spec.rb

Given a basic JSCS configuration of
```
jscs:
enabled: true
```
Instances of `SmallBuildJob` will log an exception to Resque's `failed` queue.
The exception reads "no implicit conversion of Hash into String."
The root cause turned out to be `Config::Jscs#default_content`. Instead of being
a string, it was a Ruby hash, and when a user provided no configuration file in
his `.hound.yml`, `Config::Jscs` attempted to parse that hash via `YAML.parse`,
resulting in the exception.
This change removes `Config::Jscs#default_content`, delegating to
`Config::Base#default_content`, which is already a String. It also changes the
parser used from YAML to JSON, which more closely aligns with the implementation
of `Config::Jshint` and the format of JSCS's configuration file.

Set JSCS default config as string, not hash

---

README.md

The badge has said 4.0 for many months (years?) and the Hound team does
not seem to be getting any value from Code Climate's analysis.
Anyone feel that this badge should stay?

Remove Code Climate badge

---

Gemfile.lock

This fixes the deprecation warning:
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.

Update rspec-rails to 3.4.2

---

app/models/repo.rb
db/migrate/20160513002940_add_github_id_uniqueness_on_repos.rb
db/schema.rb
lib/tasks/repo.rake
spec/lib/tasks/repo_spec.rb
spec/models/repo_spec.rb
spec/services/repo_synchronization_spec.rb

Previously, we were ensuring repo uniqueness by name, but since we are
tightly coupled to GitHub, we should be using their ids.
There was a recent bug that led to this:
* On GitHub, `thoughtbot/constable-api` repo was renamed to `thoughtbot/constable`
* On GitHub, `thoughtbot/constable` repo was renamed to `thoughtbot/constable-react`
* When we were syncing repos, we would find the `thoughtbot/constable`
and create a membership for it
* Then we would see the `thoughtbot/constable-react`. Nnot find it
by name, then look it up by `github_id` and pull up the same
`thoughtbot/constable` record and try to create a membership,
which would fail.
If we relied on `github_id` for uniquness we would eventually update the
names to match what GitHub has.

Ensure uniqueness of repos by github_id

---

app/helpers/configuration_helper.rb
app/views/pages/configuration.haml

In preparation for dropping support of JSCS,
we're removing the documenation so users don't discover it.

Remove JSCS documenation

---

CONTRIBUTING.md
app/models/linter/base.rb
app/models/linter/coffee_script.rb
app/models/linter/haml.rb
app/models/linter/ruby.rb
app/services/complete_file_review.rb
db/migrate/20160314122828_add_linter_name_to_file_reviews.rb
db/migrate/20160430171015_backfill_linter_names_add_null_constraint.rb
db/schema.rb
spec/factories.rb
spec/models/linter/eslint_spec.rb
spec/models/linter/go_spec.rb
spec/models/linter/jscs_spec.rb
spec/models/linter/jshint_spec.rb
spec/models/linter/python_spec.rb
spec/models/linter/remark_spec.rb
spec/models/linter/scss_spec.rb
spec/models/linter/swift_spec.rb

[Related Github issue](https://github.com/houndci/hound/issues/1101)
Generally speaking, for any given language, Hound supports only one linter. For
example, Rubocop will handle all `.rb` files; SCSS-lint will lint `.scss` files
and so on.
And then there's JavaScript.
For JavaScript, Hound supports three linters: JShint, JSCS, and ESlint,
each of which can be individually enabled or disabled. If both JShint and
JSCS are enabled, however, Hound code reviews will never complete for a given
build, and this is because `CompleteFileReivew#file_review` will only look up
a `FileReview` by its `filename` attribute, and when multiple linters are
working on a single file, that is not enough information. The second through nth
`FileReivew` for that file never gets found, and its `completed_at` never …

Add file_reviews.linter_name

---

db/migrate/20160513205551_add_index_for_builds_pull_request_number_and_commit_sha.rb
db/schema.rb

When completing a file review job, we find the associated build record
by pull request number and commit sha. With about 1.6 million records
in the table, this query is averaging 1820ms to execute.
This adds an index on the pull_request_number/commit_sha pair to improve
the performance of that query.

Add index for builds pr number and sha

---

spec/helpers/analytics_helper_spec.rb

`identify_hash` deserves to have own space.

Fix analytics_helper_spec describes

---

CONTRIBUTING.md
doc/SECURITY.md

There are two places in the docs where we list our linters but leave out ESLint. I've added in references in the styles of the other linters.

Add ESLint to lists of linters

---

app/assets/javascripts/directives/repo.js.coffee.erb
app/controllers/activations_controller.rb
app/controllers/subscriptions_controller.rb
app/models/analytics.rb
app/serializers/repo_serializer.rb
spec/controllers/activations_controller_spec.rb
spec/controllers/subscriptions_controller_spec.rb

In order to get correct statistics for our paid marketing efforts we
need conversion events to be tracked on the client side so that segment
can drop in the appropriate conversion pixels.
https://trello.com/c/sublWZZi

Track repo activation on the client side

---

Gemfile
Gemfile.lock
app/assets/stylesheets/admin/administrate.scss
app/views/admin/job_failures/index.haml
config/initializers/administrate.rb

Make it so things are visible on the screen, rather than scrolling
horizontally.
Uses features from the latest Administrate release, to provide custom
CSS styles.

Improve formatting of failed jobs admin page

---

app/services/ruby_config_builder.rb
spec/services/ruby_config_builder_spec.rb

When hound rescues from a `TypeError` right now it is returning a `Hash`, but if the operation had succeeded it would have returned a `RuboCop::Config`.
Change: return the default `RuboCop::Config` in `rescue` block.
See: https://github.com/houndci/hound/issues/1146 and a reproduced failure:

RubyConfigParser should return a Config, not a Hash, on error

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/directives/organization.js.coffee
app/assets/javascripts/directives/organization_list.js.coffee.erb
app/assets/javascripts/directives/repo_list.js.coffee.erb
app/models/user.rb
app/serializers/repo_serializer.rb
app/views/repos/index.haml
app/views/templates/organization.haml
app/views/templates/organization_list.haml
app/views/templates/repo.haml
app/views/templates/repo_list.haml

- Eventually we will display options for a github account level style guide configuration. Part of that change that we can implement before having the backend done is splitting the repos page by owner. This way, we can add in @smharley's work more easily when the time comes.
Changes:
- Add `organization_list` and `organization` templates and directives.
- Move some logic from `repo_list` directive (which was the top-level directive before) to `organization_list` (the top-level directive now)
- Add lodash because we have to filter objects based on property equality, and for all its other handy helpers.

Display repos grouped by repo owner

---

app/services/build_runner.rb

GitHub returns `401 - Bad credentials` status when a user with
expired/invalid token tries to set it. We should handle that case and
remove that token from the repo's memberships.

Remove users with bad tokens from repo

---

app/models/hound_config.rb
app/services/check_enabled_linter.rb
spec/models/hound_config_spec.rb
spec/models/linter/coffee_script_spec.rb
spec/services/check_enabled_linter_spec.rb

This is a change isolated from https://github.com/houndci/hound/pull/1149. The new naming is clearer and makes `HoundConfig` more readable.

Rename `enabled_for?` to `linter_enabled?`

---

app/models/owner.rb
app/services/build_owner_hound_config.rb
db/migrate/20160608183021_add_config_to_owner.rb
db/schema.rb
spec/models/owner_spec.rb
spec/services/build_owner_hound_config_spec.rb

I just realized I can split these owner level config changes up and not change anything on the user facing side, so here's the first of several smaller PR's.
Owners can now have a config repository configured. When given an
`owner` `BuildOwnerHoundConfig` will fetch the HEAD commit of the repo
and give back a `HoundConfig` built from it. If the owner does not have
a config repo or it is disabled `BuildOwnerHoundConfig` will return
false.

Add BuildOwnerHoundConfig service

---

app/models/linter/base.rb
app/models/linter/ruby.rb
app/services/ruby_config_builder.rb
spec/models/linter/ruby_spec.rb
spec/models/style_checker_spec.rb
spec/services/ruby_config_builder_spec.rb
spec/support/fixtures/legacy_rubocop_config.yml
spec/support/fixtures/thoughtbot_rubocop_config.yml
spec/support/helpers/linter_helper.rb

`RubyConfigBuilder` no longer knows anything about hound defaults or thoughtbot
defaults, it just acts as a bridge between hashes (what our
`Config::Ruby` objects produce) and `RuboCop::Config`s.
`Linter::Ruby` configures cops with the results of merging the repo's
configuration into the owner's configuration. Only some of the specs
have been rewritten, there's still more to rewrite on that end, but it does work, I just want to perfect the setup steps and make sure we're testing all scenarios.

Owner Level Ruby Configuration

---

app/models/empty_commit.rb
app/models/linter/ruby.rb
app/services/build_owner_hound_config.rb
spec/models/linter/ruby_spec.rb
spec/services/build_owner_hound_config_spec.rb

We've been getting some errors on staging when I set non-sensical values for config repos (things that either can't be parsed by the GitHub API or don't exist). This changes the way `BuildOwnerHoundConfig` works to allow for inputs like that. It also changes all behavior where `BuildOwnerHoundConfig` would previously return nil and instead returns a default `HoundConfig` (this allows us to merge into it without worrying about whether or not it's the correct type). Lastly, instead of trying to save config repos (which were getting validation errors because we don't have their GitHub ID) it just discards the config repo after grabbing the default Hound GitHub token from it.

Return empty HoundConfig when owner has no config

---

app/models/config/base.rb
app/models/config/coffee_script.rb
app/models/config/jshint.rb
app/models/hound_config.rb
app/services/check_enabled_linter.rb
app/services/normalize_config.rb
app/services/resolve_config_aliases.rb
spec/lib/js_ignore_spec.rb
spec/models/config/base_spec.rb
spec/models/config/coffee_script_spec.rb
spec/models/config/jshint_spec.rb
spec/models/hound_config_spec.rb
spec/services/build_owner_hound_config_spec.rb
spec/services/check_enabled_linter_spec.rb
spec/services/normalize_config_spec.rb
spec/services/resolve_config_aliases_spec.rb
spec/support/helpers/commit_helper.rb

Previously, `hound_config#enabled_for?` would return `true` for any value that was not:
- Explicitly set to false in the supplied config file
- A language marked as beta
Additionally, HoundConfig didn't account for aliases. This could result in someone disabling an alias (e.g. `javascript`) but still running the actual linter (e.g. `jshint`). Instead of trying to perform boolean logic about what is and is not activated, this strategy just starts with a default configuration and merges the user-specified configuration into it using a series of transforms.
Thanks to @jackvnimble for the idea!

HoundConfig merges default and user configurations

---

db/migrate/20160624165658_update_thoughtbot_owner_configs.rb
db/schema.rb

Migrate thoughtbot owner to use the guides as its owner level config.

Thoughtbot should use thoughtbot config

---

lib/tasks/resque.rake

Resque will show something like "2 of 356 Workers Working" which is
clearly false. This will clear that count, back to sane numbers.

Clear working workers count in Resque

---

app/helpers/configuration_helper.rb
app/views/pages/configuration.haml
config/style_guides/.jshintignore
lib/js_ignore.rb

Update, rephrase, standardize and cleanup the content of the docs.
This also will now always ignore `vendor/*` and `node_modules/*`.

Update and cleanup configuration

---

app/controllers/admin/blacklisted_pull_requests_controller.rb
app/dashboards/blacklisted_pull_request_dashboard.rb
app/dashboards/dashboard_manifest.rb
app/jobs/buildable.rb
app/models/blacklisted_pull_request.rb
db/migrate/20160712203443_create_blacklisted_pull_requests.rb
db/schema.rb
spec/factories.rb
spec/jobs/buildable_spec.rb

* Adds `blacklisted_pull_requests` table
* Updates `Buildable` to check if a pull request has been blacklisted
before changing the PR status or running the build. If a PR is
blacklisted, nothing will happen on the PR.
* Adds an admin dashboard to manage blacklisted pull requests

Support blacklisting pull requests

---

app/assets/javascripts/directives/repo.js.coffee.erb

We're over-reporting our "Repo Activated" events to Twitter, et. al.
because Segment maps pixels at the event level,
can't take advantage of the nice properties we were sending.
Separating the events should improve the accuracy of the measurements
on our paid marketing growth experiments.
https://trello.com/c/BANVIQKY

Separate public/private repo activated events

---

app/models/hound_config.rb
app/services/resolve_config_conflicts.rb
app/views/pages/configuration.haml
spec/models/hound_config_spec.rb
spec/services/resolve_config_conflicts_spec.rb

We now have multiple linters which can lint the same file (e.g. `jshint`
and `eslint`). It probably only makes sense to use one of these at a
time, so Hound now checks to see if there are any conflicts between
enabled linters (specifically if eslint is enabled and javascript is not
explicitly disabled) and disables the conflicts explicitly.
Other changes:
- Turn on `jshint` by default again (because I believe this is the
expected behavior)

Check for conflicting linters + resolve conflicts

---

app/services/resolve_config_conflicts.rb
spec/models/hound_config_spec.rb
spec/services/resolve_config_conflicts_spec.rb

The ResolveConfigConflicts object was working in the sense that it
disables linters which conflict with configured and enabled linters.
However, it was not correctly including the config options for the
configured and enabled linter. An example:
A .hound.yml of:
eslint:
enabled: true
would accurately disable `jshint`. However, it would not enable `eslint`.
This change allows it to do both.

Include original config options after transform

---

app/views/pages/configuration.haml

The section about Go in the docs ought to read:
To disable Go style checking, add the following to your `.hound.yml`
```
go:
enabled: false
```

Go, Don't Go

---

app/helpers/configuration_helper.rb
app/views/pages/configuration.haml

New customers will now use the default linter config.

Update RuboCop default config docs

---

app/models/config/jshint.rb
app/models/jshint_config_builder.rb
app/models/linter/jshint.rb
spec/models/config/jshint_spec.rb
spec/models/jshint_config_builder_spec.rb

Most of our configs are initialized by passing in a `hound_config`. In a
lot of cases this makes sense, but it makes it difficult to do things
like merge configs, which is a crucial part of enabling owner level
configurations.
- Make Config::Jshint initialize with a string of content
- Allow `parse` to take other arguments, but default to the`raw_content` that the object was initialized with (similar to how `serialize` works already)
Right now the `JshintConfigBuilder` is overly specialized. I'd like to start expanding this to other linters, slowly making `JshintConfigBuilder` more generic, and then ultimately remove what is the `ConfigBuilder` right now with the generic version of `JshintConfigBuilder`

Initialize Jshint config with content

---

app/models/linter/coffee_script.rb
app/models/violation.rb
app/services/complete_file_review.rb
spec/features/account_spec.rb
spec/models/violation_spec.rb
spec/services/complete_file_review_spec.rb

Rather than updating `build.violations_count` after each violation,
do it once after the file review is complete.
This should alleviate the DEADLOCK error, like:
```
PG::TRDeadlockDetected: ERROR: deadlock detected DETAIL: Process 2333
waits for ShareLock on transaction 19601816; blocked by process 2430.
Process 2430 waits for ExclusiveLock on tuple (223360,8) of relation
16407 of database 16385; blocked by process 2333. HINT: See server log
for query details. : UPDATE "builds" SET "violations_count" = $1,
"updated_at" = $2 WHERE "builds"."id" = $3
```
Since we'll be updating that model less frequently during the build.

Store violations count when file review completes

---

app/services/build_runner.rb
spec/services/build_runner_spec.rb

Updates `BuildRunner` to not complete the build (comment or set success
status). When #1206 is merged, all linters will be service based and
completing the build is part of the `CompleteFileReview` that occurs
when a service wraps up a job.
This should also reduce (eliminate?) the double commenting issues.

Don't complete the build early

---

app/models/linter/jshint.rb
spec/models/linter/jshint_spec.rb

Background
This builds on work done in https://github.com/houndci/hound/pull/1191 to allow owner level configurations for the `jshint` linter.
Changes
- Add a `owner_config` and `owner_hound_config` methods to `Linter::Jshint`
- Move `config` to `local_config`
- Change `config` to be the merged result of the `owner_config` and the `local_config`

Use merged config in jshint linter

---

app/services/build_runner.rb
spec/services/build_runner_spec.rb

When there are not reviews scheduled for a build, we never set the
status back from pending.

Set status to success when no files to review

---

app/models/commit_file.rb
app/models/patch.rb
spec/models/commit_file_spec.rb
spec/models/patch_spec.rb

`CommitFile.line_at` has a point of improvements changing the way
we create and access the data structure, from an array to hash, this
means an improvement from O(n) to O(1).
In order to get this improvement we need to change how
`Patch.changed_lines` construct their data structure.

Speed Improvements for CommitFile and Patch models. Closes #1223

---

app/assets/stylesheets/components/_components.scss
app/assets/stylesheets/components/_current-plan.scss
app/assets/stylesheets/components/_pricing.scss
app/assets/stylesheets/pages/accounts/_show.scss
app/views/accounts/show.html.erb
app/views/shared/_plan_vertical.html.erb

This is mostly styling of static markup (hence WIP). Needs to be integrated with pricing implementation once that's finished, also many need converting to react components.
**Notes:**
- The `.current-plan` `<span>` tag is added to the current plan.
- The `.current` class is applied to the current plan.
**Todo:**
**Depends on #1231 so rebase from there.**

WIP: Add new pricing plans to account page

---

lib/migrate_stripe_customers.rb
lib/migrate_stripe_subscription.rb

Previously, the Rake task to migrate Stripe customers onto the new payment plans only looped through the first 100 customers, which meant we never updated the other 800+ customers and the script got stuck in an infinite loop. Update the Rake tasks to pagination through the rest of the Stripe elements.

Loop through Stripe elements

---

lib/migrate_stripe_customers.rb

Previously, were were calling `all` on `Stripe::Customers`, which is a class that does not exist. Update the "migrate Stripe customers" to use the correct, `Stripe::Customer`, class.

Fix customer typo

---

app/assets/javascripts/components/update_account_email.js.jsx
app/assets/javascripts/components/update_account_email_message.js.jsx
spec/features/account_spec.rb
spec/support/user_on_page.rb

Previously, `this` was not bound to the email update event, which meant the resulting function was called in the correct context and users could not update their email address. Bound `this` to the email update.
https://trello.com/c/FjeiUk41

Bind `this` to email update event

---

app/assets/javascripts/components/repo.js.jsx
app/assets/stylesheets/pages/repos/_index.scss
app/views/repos/_onboarding.haml
config/locales/en.yml

Before:
After:
The onboarding flash has a reference to the old pricing structure.
Removed the explicit dollar amount, replaced with a link to the account page pricing breakdown
Also removes the price tags next to the 'activate' buttons:
Before:
After:

Remove references to old pricing structure

---

.ruby-style.yml

Before, we were using the default Rubocop Ruby styles, which included rules for Rails 5. This was causing Hound to throw a warning because the app is only on Rails 4. Disabled the rule until the app we upgrade the app.

Disable Rubocop HTTP positional arguments check

---

config/application.rb

This fixes lib files not being available in Rails 5 production without
explicitly requiring them.
This comes with the caveat that everything in lib will be loaded when the
application boots, but in our case that's just a few rake tasks so we aren't too
concerned about it for the convenience this provides.

Add lib to eagerload paths

---

app/services/complete_build.rb
app/services/complete_file_review.rb
spec/services/complete_build_spec.rb
spec/services/complete_file_review_spec.rb

`BuildReport` was confusing due to us having a `Build` model.
Does it mean it's a noun "the build report", or an action of
"building a report"?
We already have `CompleteFileReview`, so for parity with that it makes
sense to rename this to `CompleteBuild` to avoid ambiguity.

Rename BuildReport to CompleteBuild

---

app/models/config/haml.rb
app/models/missing_owner.rb
app/models/owner.rb
spec/models/config/haml_spec.rb
spec/models/missing_owner_spec.rb
spec/models/owner_spec.rb

Before, the Haml linting always used Hound's default or the repository's own configuration. This meant we had to specify organisation-wide configurations in each individual repository. Updated the Haml configuration to allow configuration at an organisational level.

Use owner configuration for Haml linting

---

app/models/config/scss.rb
spec/models/config/scss_spec.rb

Before, the SCSS linting always used Hound's default or the repository's own configuration. This meant we had to specify organisation-wide configurations in each individual repository. Updated the SCSS configuration to allow configuration at an organisational level.

Use owner configuration for SCSS linting

---

app/models/config/eslint.rb
spec/models/config/eslint_spec.rb

Before, the JavaScript linting always used Hound's default or the repository's own configuration. This meant we had to specify organisation-wide configurations in each individual repository. Updated the JavaScript configuration to allow configuration at an organisational level.

Use owner configuration for JavaScript linting

---

app/models/config/base.rb
app/models/config/coffee_script.rb
app/models/config/haml.rb
app/models/config/ruby.rb
app/models/config/scss.rb
app/models/config/tslint.rb
app/models/linter/base.rb
app/models/linter/coffee_script.rb
app/models/linter/ruby.rb
spec/models/config/base_spec.rb
spec/models/config/coffee_script_spec.rb
spec/models/config/ruby_spec.rb
spec/models/config/tslint_spec.rb

Before, we were overriding the constructor in every child class, which was a waste of time. Updated the base class to now take an optional owner argument.

Move configuration owner into base

---

app/models/linter/eslint.rb
app/models/linter/haml.rb
app/models/linter/scss.rb

Before, we set up several configurations to accept an owner. This was all well and good, but we did not actually pass an owner through. Updated the SCSS, ESLint, and Haml linters to provide an owner to their configurations.

Pass the owner through to the configuration

---

app/models/config/swift.rb
app/models/linter/swift.rb
spec/models/config/swift_spec.rb

Before, the Swift linting always used Hound's default or the repository's own configuration. This meant we had to specify organisation-wide configurations in each individual repository. Updated the Swift configuration to allow configuration at an organisational level.

Use owner configuration for Swift linting

---

Rakefile
config/environments/production.rb
lib/redirect_to_configuration.rb

To fix Heroku deployment. Also - getting rid of some deprecations and warnings.

Hooking webpack's build step before asset precompilation

---

app/models/config_builder.rb
app/models/linter/base.rb
app/models/linter/coffee_script.rb
app/models/linter/eslint.rb
app/models/linter/haml.rb
app/models/linter/ruby.rb
app/models/linter/scss.rb
app/models/linter/swift.rb
app/models/linter/tslint.rb
spec/models/config_builder_spec.rb

Before, we had started to pass the owner through to the individual configurations. This meant we were overriding the base class with similar methods in the children. Updated the configuration builder to accept an owner and updated the base lint to pass an owner.

Update base linter config

---

app/models/config/python.rb
app/models/linter/python.rb
spec/models/config/python_spec.rb

Before, the Python linting always used Hound's default or the repository's own configuration. This meant we had to specify organisation-wide configurations in each individual repository. Updated the Python configuration to allow configuration at an organisational level.

Use owner configuration for Python linting

---

app/models/config/base.rb
app/models/config/coffee_script.rb
app/models/config/credo.rb
app/models/config/eslint.rb
app/models/config/haml.rb
app/models/config/jshint.rb
app/models/config/python.rb
app/models/config/remark.rb
app/models/config/ruby.rb
app/models/config/scss.rb
app/models/config/swift.rb
app/models/config/tslint.rb
app/models/config_content.rb
app/models/config_content/remote.rb
spec/models/config/base_spec.rb
spec/models/config/coffee_script_spec.rb
spec/models/config/python_spec.rb
spec/models/config_content/remote_spec.rb
spec/models/config_content_spec.rb

Before, we had started to override the loading of config content in each of the child classes. This meant there had become some divergence from the base definition. Created a config content loader and moved the loading and merging into the parent class.

Move loading of content into base config

---

app/models/linter/base.rb
app/services/build_config.rb
spec/models/linter/base_spec.rb
spec/services/build_config_spec.rb

Before, the config builder was a model and the name implied that it return an instance of a config builder. The config builder actually returned an instance of a specific config. Moved the class into the `services` directory and gave it a more appropriate name.

Give the config builder an appropriate name

---

app/models/config/base.rb
app/models/missing_owner.rb
app/models/owner.rb
spec/models/config/base_spec.rb
spec/models/config/coffee_script_spec.rb
spec/models/config/eslint_spec.rb
spec/models/config/haml_spec.rb
spec/models/config/python_spec.rb
spec/models/config/remark_spec.rb
spec/models/config/ruby_spec.rb
spec/models/config/scss_spec.rb
spec/models/config/swift_spec.rb
spec/models/config/tslint_spec.rb
spec/models/linter/coffee_script_spec.rb
spec/models/linter/eslint_spec.rb
spec/models/linter/haml_spec.rb
spec/models/linter/remark_spec.rb
spec/models/linter/ruby_spec.rb
spec/models/linter/scss_spec.rb
spec/models/linter/swift_spec.rb
spec/models/linter/tslint_spec.rb
spec/models/missing_owner_spec.rb
spec/models/owner_spec.rb

There was a infinite-loop situation, where we would attempt to keep
calling `content` (and subsequently `owner_config`) for each owner.
Since we moved to `MissingOwner`, we'd pass that in when there was no
owner, and thus loop infinitely passing around `MissingOwner` instance.
This prevents the above situation and returns empty config for
`MissingOwner`.

Don't fetch config when there is no owner

---

Rakefile
circle.yml
lib/tasks/js.rake

- Add `js:spec` task to wrap `npm run build && npm run test`
- Add `builder:audit` task to the `default` task from the get go.

Run react tests in `rake`'s default task

---

lib/tasks/webpack.rake
package.json
webpack.config.js

Hoping not creating source maps in production will help the bundle behave normally (also, only build said bundle once in Heroku).

Webpack 2.x production build fixes (II)

---

app/assets/stylesheets/components/_code.scss
app/helpers/application_helper.rb
app/helpers/configuration_helper.rb
app/views/application/_footer.haml
app/views/application/_header.haml
app/views/home/index.haml
app/views/pages/configuration.haml

* Remove default config docs for JSHint, since we're now starting new customers with JSHint defaults.
* Use safe new tab opening options

Update config docs

---

app/models/config/go.rb
app/models/linter/python.rb
spec/models/config/go_spec.rb
spec/models/linter/go_spec.rb

Before, the Python and Go linters had their own specific configurations when they did not need to. Updated both of the linters to inherit the configuration implementation from their bases.
https://trello.com/c/PMwYwgPL

Always merge configurations

---

app/models/config/coffee_script.rb
spec/models/config/coffee_script_spec.rb

https://github.com/houndci/hound/commit/4632b20bf5c4fb00723ad4002547c445ddf5c7ab#diff-31c9aca594d7a0025b941e49336e8cc5R39 moved all parsing to be yaml - but coffeelint config is stored as json

Fix coffeelint json config parsing

---

app/models/config/ruby.rb
spec/models/config/ruby_spec.rb

There was a logical error, where owner's (org-level) config was merged
with the repo config first, and then merged with the repo's inherited
config. Thus, the last step of merging with inherited allowed for the
owner cofig to override the inherited (which is the repo's config still).

Ensure inherit config is merged before owner's

---

spec/models/linter/base_spec.rb
spec/models/linter/coffee_script_spec.rb
spec/models/linter/credo_spec.rb
spec/models/linter/eslint_spec.rb
spec/models/linter/go_spec.rb
spec/models/linter/haml_spec.rb
spec/models/linter/jshint_spec.rb
spec/models/linter/python_spec.rb
spec/models/linter/remark_spec.rb
spec/models/linter/ruby_spec.rb
spec/models/linter/scss_spec.rb
spec/models/linter/swift_spec.rb
spec/models/linter/tslint_spec.rb
spec/support/shared_examples.rb

While reviewing the specs for the suite of linters there is common
behavior that is repeatedly tested that is ripe for extraction to
something like a shared example.
To reduce boilerplate I've started with one quick win - a small test to
assert that linters allow only certain types of files and/or extensions.

Dry up testing common linter behavior

---

app/jobs/flog_review_job.rb
app/models/hound_config.rb
app/models/linter/base.rb
app/models/linter/flog.rb
spec/models/linter/flog_spec.rb

Before, we only checked Ruby files using Rubocop. This only allowed us to comment on the style of the files. Added a Flog integration which will comment on Ruby methods that are too complex.

Set Hound up to Flog Ruby changes

---

app/jobs/reek_review_job.rb
app/models/config/reek.rb
app/models/hound_config.rb
app/models/linter/reek.rb
spec/models/linter/reek_spec.rb

In addition to the soon-to-be merged flog linter, this commit enables using reek to surface potential code smells.
More information on reek is available here: https://github.com/troessner/reek

Add reek as a linter to main Hound app

---

app/services/complete_build.rb
spec/services/complete_build_spec.rb

Some jobs are failing with what appears to be an error message from
GitHub complaining about an empty review. We don't have great logging
capabilities into the job failures, so I'm making an assumption that not
submitting a review with empty comments with fix this.
> undefined method `map' for "You need to leave a comment indicating the
> requested changes."

Don't submit a review for zero violations

---

CONTRIBUTING.md

To avoid confusion for new contributors on how the deployment of the
application works, an update to the documentation was required.

Document deployment

---

CONTRIBUTING.md

GitHub recently updated their Markdown parser which appears to have
broken some of the formatting we had. For example, we use ordered list
markers that always begin with "1" and when rendered, the ordered
numbers are automatically created. Due to the parsing changes, some
lists had indentation errors that were causing the order of the markers
to not be linear.
See: https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown
- - -

Fix Markdown rendering

---

app/models/hound_config.rb

Before TSLint was defined but was never being triggered since it wasn't
in this "master" list.

Add TSLint to the list of linters to run

---

app/models/payment_gateway_subscription.rb
spec/models/payment_gateway_subscription_spec.rb

We've got some dups in there, this should clean it up.

Store unique repo ids in Stripe's metadata

---

CONTRIBUTING.md
app/models/config/ruby.rb
app/models/hound_config.rb
app/models/style_checker.rb
spec/models/hound_config_spec.rb

This makes it straight forward to see which linter is enabled by
default.
This gets away from the legacy "beta" concept and makes it easier to
enable/disable future linters.

Store linters and their default config in a hash

---

app/controllers/admin/application_controller.rb
app/controllers/admin/masquerades_controller.rb
app/controllers/application_controller.rb
app/views/admin/application/_sidebar.html.haml
app/views/application/_header.haml
config/locales/en.yml
config/routes.rb
spec/controllers/subscriptions_controller_spec.rb
spec/features/admin_masquerades_spec.rb
spec/requests/admin/masquerades_spec.rb

This adds a route that admins can go to that will put them in a mode where they
masquerade as the user they provided. They can then browse hound as if they were
that user, and then click "Stop Masquerading" to return to their own account.
https://trello.com/c/h9VtPK6F/800-as-an-admin-i-would-like-to-masquerade-as-a-user-so-that-i-may-help-debug-issues-that-they-are-running-into

Masquerading as a user

---

app/models/owner.rb
app/services/repo_synchronization.rb
spec/models/owner_spec.rb
spec/services/repo_synchronization_spec.rb

The `RepoSynchronization` service object has recently run into an issue
where a user has had a repo owner with a different github_id, but a name
for the Owner/Org that is the same as a previous Owner record. This has
caused an exception during the synchronization process that was not
recovered.
This commit will rescue that exception in the RepoSynchronization service
object, and will continue the `each` loop if it encounters it.
Down in the Owner model class, however, the upsert that creates this
exception will send the error to Raven along with some additional info
on the offending repo - the github_id and the name.

Rescue & handle RecordNotUnique error in repo sync

---

app/models/config/python.rb
app/services/sanitize_ini_file.rb
spec/models/config/python_spec.rb
spec/services/sanitize_ini_file_spec.rb

The configuration that Flake8 accepts from the config file can have
certain options on multiple lines, like:
```
[flake8]
ignore =
E221,
E222
```
The library we use to parse the ini file isn't able to handle that case
and errors out.
This solution puts the multi-line options on one line,
as well as removes all the comments from the config file.

Sanitize Flake8 config

---

app/jobs/stylelint_review_job.rb
app/models/config/stylelint.rb
app/models/hound_config.rb
app/models/linter/stylelint.rb
app/services/resolve_config_conflicts.rb
spec/models/linter/stylelint_spec.rb

We worked with @gmq to add support for https://stylelint.io/
It works quite similar to tslint and eslint.
We've rolled this in our infrastructure and it's looking good
this should close https://github.com/houndci/hound/issues/1037

Add support for stylelint

---

app/jobs/linters_job.rb
app/models/config/slim_lint.rb
app/models/hound_config.rb
app/models/linter/slim_lint.rb
spec/models/linter/slim_lint_spec.rb

Also adds the `LintersJob` class and uses the `linters` queue.
https://github.com/houndci/linters/pull/105
Closes #923

Add slim-lint support

---

app/assets/javascripts/components/repos_container.jsx
app/models/tier.rb
app/queries/repos_with_membership_or_subscription_query.rb
app/serializers/repo_serializer.rb

Fixes a handful of N+1 issues for the repos.json endpoint.
Also removes the `price_in_dollars` fields from the response. It's
calculated from the old $12/repo business logic. Eventually the whole
`Plan` object should be removed, but that's out of scope for this PR.
For my user, this reduces the number of queries from 1391 to 7.

Performance tune the repos endpoint

---

app/helpers/configuration_helper.rb
app/models/config/sass_lint.rb
app/models/hound_config.rb
app/models/linter/sass_lint.rb
app/services/resolve_config_conflicts.rb
app/views/pages/configuration.haml
spec/models/config/sass_lint_spec.rb
spec/models/linter/sass_lint_spec.rb
spec/services/resolve_config_conflicts_spec.rb

This PR adds Hound Support for Sass-lint using the single `linters` queue.
It includes an update to `/configurations` letting people know how to enable and configure Sass-lint.

Support Sass-lint

---

app/models/build.rb
app/models/pull_request.rb
app/services/complete_build.rb
app/services/complete_file_review.rb
db/migrate/20170505220736_add_error_to_file_reviews.rb
db/schema.rb
lib/github_api.rb
spec/lib/github_api_spec.rb
spec/models/build_spec.rb
spec/models/pull_request_spec.rb
spec/requests/builds_spec.rb
spec/services/complete_build_spec.rb
spec/services/complete_file_review_spec.rb
spec/support/fake_github.rb
spec/support/helpers/github_api_helper.rb

When a linter encounters an unexpected error, like invalid config
syntax, we will receive it in the `error` attribute in the payload.
Then we'll report it to the user via the main comment that goes into the
PR review body.

Report linter errors as the main PR review comment

---

app/models/pull_request.rb
spec/models/pull_request_spec.rb

GitHub doesn't like nil for `body` property when creating a file review.
It gives us an error like:
```
422 - Invalid request. For 'properties/body', nil is not a string.
```

Pass empty string to review body when no errors

---

app/models/pull_request.rb
app/models/review_body.rb
spec/models/pull_request_spec.rb
spec/models/review_body_spec.rb

GitHub limits the review body (main comment) to be 65,536 characters or
less. Otherwise, an error gets thrown.
This change will truncate our errors to fit within that limit, while
still tryign to show the error.

Limit the size of GitHub review body comment

---

app/views/layouts/application.haml

- Declaring the language attribute on the `html` element allows
assistive technology to understand the human language of the page.
Screen readers use this information to read out the text with correct
pronunciation.
- Marking the language can also assist user agents in providing
definitions using a dictionary.

Add `lang` attribute to `html` element

---

app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/pages/_builds.scss
app/assets/stylesheets/pages/_docs.scss
app/assets/stylesheets/pages/home/_home-languages.scss
app/assets/stylesheets/pages/repos/_organization.scss

By increasing the contrast between foreground and background colors we
help those with low vision impairments and color deficiencies read and
navigate our content.
This change meets WCAG 2.0 AA contrast ratio thresholds and removes 12
violations thrown by [axe-core](https://github.com/dequelabs/axe-core)
when run on the home page.

Fix color contrast of text

---

.rubocop.yml

After the May 31 update of the version of rubocop that Hound uses, I found that I needed to update these configurations.
This goes a few steps further than #1367, re-sorting the names alphabetically, and also removing/updating option names that caused warnings.

Update rubocop config names and options for new version

---

.rubocop.yml
app/models/config/parser.rb
spec/models/config/ruby_spec.rb

RuboCop config can now contain serialized symbols in its YAML.
Closes #1370

Whitelist serialized symbols when parsing YAML

---

app/assets/stylesheets/base/_base.scss
app/assets/stylesheets/base/_buttons.scss
app/assets/stylesheets/base/_forms.scss

Commit adaa96040cd14ef36d8e47a21b59bf5b3110e422 accidentally left all buttons and text inputs to fall back to `sans-serif` as a font, rather than use the font the rest of the app uses.
This commit adds two partials which mimics how Bitters is structured: https://github.com/thoughtbot/bitters/tree/master/core

Fix button and input font

---

spec/support/fixtures/thoughtbot_rubocop_config.yml

Why:
RuboCop has renamed this key
https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md#changes-12
This PR:
Changes DeprecatedHashMethods to PreferredHashMethods

DeprecatedHashMethods -> PreferredHashMethods

---

.hound.yml
.scss-lint.yml

This is a clone of thoughtbot's configuration from our guides
(https://github.com/thoughtbot/guides/), with the addition of
BEM-related linters enabled.

Add scss-lint configuration

---

app/views/home/index.haml
app/views/pages/configuration.haml
app/views/repos/_onboarding.haml

Properly marking up headings provides semantic meaning to things like
assistive technology. This also allows screen readers to navigate
through headings, providing screen reader users an efficient way to
find and parse content. Skipping heading levels, or marking up
non-headings in heading elements can lead to confusion.
This commit also changes content within two headings to better convey
the content in their section:
- "Hound keeps your code style in check." is now "Pricing."
- "Write code, submit a pull request, get review from Hound." is now
"How it works."

Improve headings outline and content

---

app/views/layouts/application.haml
app/views/repos/index.haml

This is being used to inject the `repo-index` class, which is not used.

Remove unnecessary content_for helper

---

app/assets/stylesheets/base/_tables.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/pages/_docs.scss

- Remove unused variables
- Group typography variables
- Move partial-specific variables into their partial, rather than
defining them alongside global variables
- Remove `$large-border-radius` which was only used once and only added
`1px` to `$base-border-radius`

Clean up Sass variables

---

app/assets/stylesheets/components/_footer.scss
app/views/application/_footer.haml

- Remove unnecessary over-qualified CSS selectors, e.g. `ul.footer-nav`.
- Wrap navigation items in a proper `nav` element, which maps to the
navigation role in the accessibility tree.
- Remove unnecessary `article` element.
- Consistently use double quotes.

Simplify footer styling

---

app/views/layouts/application.haml

Adding the `main` element helps to establish the semantic structure of
the document. It also maps to the `main` ARIA landmark, which some
assistive technologies like screen readers surface to the user and
allow them to navigate using them.
See: https://dequeuniversity.com/assets/html/jquery-summit/html5/slides/landmarks.html

Add a `main` landmark

---

app/controllers/admin/application_controller.rb
app/views/admin/application/_navigation.html.haml
spec/features/admin_authorization_spec.rb

The Administrate update changed the return value from
`namespace.resources` to return an array of `Resource` objects instead
of resource names. This updates the helpers and ensures that if the
admin navigation gets clobbered in the future a test fails.

Update helper to use Resource objects

---

app/assets/stylesheets/base/_typography.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_app-nav.scss
app/assets/stylesheets/components/_button.scss

Increasing the width and offsetting the focus from the element helps to
establish more contrast, aiding people with low vision.

Redesign focus styles

---

app/models/review_body.rb
spec/models/pull_request_spec.rb
spec/models/review_body_spec.rb
spec/requests/builds_spec.rb

The previous algorithm wasn't quite correct and difficult to understand.
This simplifies it a bit, and only displays the errors that fit within
the character limit.
Also, simplify the line delimiter to be newline `\n` character rather
than `<br>` tag.

Simplify limiting of review body comment

---

app/assets/javascripts/components/repo.jsx
app/assets/stylesheets/components/_badge.scss
app/assets/stylesheets/components/_components.scss
app/assets/stylesheets/pages/repos/_index.scss
app/assets/stylesheets/utilities/_margin.scss

This is an alternative approach to https://github.com/houndci/hound/pull/1296.
**Note:** This is just the design implementation. Functionality for the following items is still needed:
- The `ariaDescribedby` attribute in the React component doesn’t yet render anything.
- The `idName ` attribute in the React component doesn’t yet render anything.
- The logic for only rendering this badge when a repo is indeed private is not implemented (i.e. “Private” is showing on every single repo right now).

Add private badge to repos list

---

app/models/user_token.rb
app/services/build_owner_hound_config.rb
lib/github_api.rb
spec/models/user_token_spec.rb
spec/services/build_runner_spec.rb

Also, rescue `Octokit::Unauthorized` when checking if config is
reachable, because if the token gets removed from GitHub's side then
we'll encounter the unauthorized error (i.e. 401 - Bad credentials).
In `GithubApi` make `client` method private, since we shouldn't be
calling it directly -- defeats the purpose of our wrapper.

Find the token that can reach the repo

---

app/assets/stylesheets/base/_base.scss
app/assets/stylesheets/base/_fonts.scss
app/assets/stylesheets/base/_forms.scss
app/assets/stylesheets/base/_tables.scss
app/assets/stylesheets/base/_typography.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_app-nav.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_pricing.scss
app/assets/stylesheets/pages/_builds.scss
app/assets/stylesheets/pages/accounts/_show.scss
app/assets/stylesheets/pages/home/_home-hero.scss
app/assets/stylesheets/pages/home/_home-languages.scss
app/assets/stylesheets/pages/home/_home-objects.scss
app/assets/stylesheets/pages/repos/_index.scss
app/assets/stylesheets/pages/repos/_onboarding.scss
app/assets/stylesheets/pages/repos/_organization.scss
app/assets/stylesheets/pages/repos/_tools.scss
app/views/layouts/application.haml

I find Lato—the current typeface used across the app—to be a tad too friendly and wobbly (the flow and alignment between characters is inconsistent); lacking structure. Given those characteristics, this makes text feel disjointed from the strong, hefty Hound logo. I also find Lato to be quite thin and hard to read sometimes.
I recently came across the [Tofino](http://tofino.losttype.com/) typeface and tried it out on the Hound app. I think improves readability, but also pairs really well with the Hound logo. Even better, we can remove a bunch of CSS that tweaked letter spacing because Tofino is better built.
**Note:** I only have a free trial/personal version of Tofino, which I used to try it out on the app. We’d need to purchase a commercial license which is a flat $80, and also add it …

Change primary typeface

---

Gemfile.lock

Test were failing locally, because `.env.local` was not being ignored
when tests run. Seems to be fixed on upgrade.

Update dotenv gem

---

app/views/pages/configuration.haml

The key should be `credo:` not `elixir:`.

Update Elixir/Credo docs

---

Gemfile.lock
app/services/repo_activator.rb
lib/github_api.rb
spec/features/plans_spec.rb
spec/features/user_activates_a_repo_spec.rb
spec/services/repo_activator_spec.rb
spec/support/fake_github.rb
spec/support/helpers/github_api_helper.rb

When collaboratore is added to a repo, GitHub now requires the
collaborator to accept the invitation.
This is keeping us from allowing users to activate their repos.

Accept invitation when added as collaborator

---

app/models/pull_request.rb
spec/models/style_checker_spec.rb
spec/services/build_runner_spec.rb

Looks like `PullRequest#repository_owner_name` was removed in 68e3136 and is no longer referenced.

Remove unused PullRequest method

---

app/dashboards/owner_dashboard.rb
app/models/owner.rb
app/models/repo.rb
config/locales/en.yml

The predicate version of attributes don't sort or update properly.
Also, `active_private_repos_count` reads slighly more natural than
`private_active_repos_count`.

Use non-predicate attributes for Administrate

---

Gemfile.lock
circle.yml
config/initializers/new_framework_defaults.rb

* Upgrade DatabaseCleaner to remove on the the deprecation warnigns
* `halt_callback_chains_on_return_false` is deprecated and will be
removed in Rails 5.2

Handle Rails deprecation warnings

---

app/models/commit_status.rb
spec/models/commit_status_spec.rb
spec/services/build_runner_spec.rb
spec/services/complete_build_spec.rb

Sometimes the user's or Hound's token isn't privileged to set the
GitHub PR status for a given repo. Status isn't critical, and shouldn't
fail the rest of the build -- as long as we can access the files and
make comments.
We're actually seeing a lot of status "Not Found" errors that prevent
builds from finishing, thus this is measure to mitigate that.
This will reduce the job failure noise and allow us to identify which
repos we can't _actually_ review.

Ignore GitHub status update errors

---

app/models/owner.rb
app/models/repo.rb

This clashes with Ruby's built-in `private`.
In stead of calling the `private` keyword, we effectively are calling
our class method and not hiding our methods.
Addresses #1442

Remove the private class method on Repo

---

app/queries/recent_builds_by_repo_query.rb

10 unique latest builds seems like enough for most use-cases.
It's very likely that we can find 10 unique PR builds from the user's
last 1000 rebuilds, and this helps limit the first sub-query.

Limit the number of builds ids for rebuild query

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

You want faster tests?
This is how you get faster tests!
P.S. Rails 5.1 now shares the database connection with test threads.

Remove database_cleaner

---

app/controllers/deleted_subscriptions_controller.rb
app/services/delete_subscriptions.rb
config/routes.rb
spec/factories.rb
spec/features/user_activates_a_repo_spec.rb
spec/features/user_deactivates_a_repo_spec.rb
spec/rails_helper.rb
spec/requests/subscriptions_spec.rb
spec/services/delete_subscriptions_spec.rb

We sometimes delete/cancel user subscriptions directly from Stripe.
Stripe is nice enough to notify us of this via a webhook.
This ensures we cleanup properly on our end -- delete all the
subscriptions by the give stripe token and deactivate the related repos.

Handle Stripe hook for deleted subscription events

---

spec/features/repo_list_spec.rb

There is an issue when a org-wide config is being enabled on the page.
When AJAX request completes we show a green checkmark and we use that in
the test to wait for AJAX to finish.
The issue shows up when the toggle is first enabled, which causes the
checkmark to be show (thus it's present on the page). Then when we
elect a repo from the dropwdown, which will remove the checkmark and
show it again when the request is done. Thus, we need to add step that
verifies/waits that the checkmark is gone when we select the config
repo.

Fix intermittent test failure on config dropdown

---

.rubocop.yml
app/models/config/jshint.rb
spec/models/linter/jshint_spec.rb

JSHint requires its config file to be in JSON format.
It can have comments, but `JSON.parse` strips those out.
`YAML.load` chokes on JSON with comments, but `JSON.parse` is fine.

Parse JSHint's config as JSON

---

circle.yml

CI builds are breaking because we're trying to fetch apt packages which no longer exist. Updating the apt-cache first stops this from happening.

Update apt before installing from it.

---

.scss-lint.yml
app/assets/stylesheets/base/_fonts.scss

The CSS `font-display` property was added in the CSS Fonts Module
Level 4 specification and is used to "…determine how a font face is
displayed, based on whether and when it is downloaded and ready to use."
By setting `font-display` to `swap`, we're telling the browser to render
the next availabel system fallback font until the custom font loads.
This fully removes the "Flash of Invisible Text," or FOIT.
Spec: https://www.w3.org/TR/css-fonts-4/#font-display-desc
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
Support: https://caniuse.com/#feat=css-font-rendering-controls

Set `font-display` to `swap`

---

package.json

Declaring Node as an engine is causing Yarn to error when running
`bin/setup`.
https://docs.npmjs.com/files/package.json#engines

Remove package.json engines

---

Gemfile
Gemfile.lock
circle.yml
spec/features/plans_spec.rb
spec/features/repo_list_spec.rb
spec/rails_helper.rb
spec/support/helpers/authentication_helper.rb

The future of QT and capybara-webkit is unknown.
Selenium with Chrome (headless) seems like a great alternative.
Ensure the repos list landing page (after sign in) finishes loading the
list of repose (via Ajax) for JS tests. Otherwise, a JS alert popup with
a failure causes tests to fail. This actually happens in Chrome on
production when navigating from the repos page before the AJAX request
to get the repos finishes (the `Your repos failed to load.` alert).

Switch to chrome webdriver for JS feature tests

---

app/services/repo_activator.rb
spec/services/repo_activator_spec.rb

If Hound already can access the repo, we don't need to accept an
invitation -- when invitation doesn't exist the activation process blows
up.

Activate repo when there is no invitation

---

app/assets/stylesheets/pages/repos/_index.scss

Don't cut off repo names

---

app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/pages/_docs.scss
app/controllers/pages_controller.rb
app/models/linter_version.rb
app/views/pages/configuration.haml
spec/models/linter_version_spec.rb

Parsing most linter versions from `Gemfile.lock` and `yarn.lock`.
Golint has no semver-like version, so we don't display any version.
Credo, Flake8 and SwiftLint are hard-coded for now, because they don't
often change.
Re-ordered the linters on the configuration doc page for a better flow.

Show linter versions in the configuration docs

---

app/models/config/parser.rb
spec/models/config/jshint_spec.rb

This can happen if a user provided a `config_file` entry, but the file
cannot be found at that path (in the repo on the branch).
Hound shouldn't error in such a case.
Addresses: https://sentry.io/hound-1/production/issues/400232909

Handle parsing empty JSON config

---

app/models/hound_config.rb
app/models/missing_owner.rb
app/models/owner.rb
app/models/style_checker.rb
app/services/build_owner_hound_config.rb
app/services/complete_build.rb
spec/models/hound_config_spec.rb
spec/services/build_owner_hound_config_spec.rb
spec/services/complete_build_spec.rb
spec/support/helpers/linter_helper.rb

If org-level configuration is enabled, then all enabled repos that fall
under that org should respect and use its `.hound.yml` file.

Inherit .hound.yml from org-level repo

---

app/models/config/parser.rb
spec/models/config_content_spec.rb

If the config file isn't found, or it's blank, for some reason, we
should treat it as an empty config and continue.

Ensure we handle a no/empty config file

---

.rubocop.yml

This was lost in the recent RuboCop upgrade.
Maybe they changed defaults?

Update .rubocop.yml for trailing comma

---

CONTRIBUTING.md
app/jobs/go_review_job.rb
app/models/config/golint.rb
app/models/hound_config.rb
app/models/linter/golint.rb
app/services/resolve_config_aliases.rb
app/views/pages/configuration.haml
spec/models/config/golint_spec.rb
spec/models/linter/go_spec.rb
spec/support/linters.rb

Point Golint at the `linters` queue, which is handled by the `linters`
service.
This is a companion to https://github.com/houndci/linters/pull/188

Rename Go to Golint

---

app/models/config/reek.rb
app/models/linter/reek.rb
spec/models/linter/reek_spec.rb

Not sure why it was `""`, but that was preventing us from using Reek
config correctly.

Serialize Reek config correctly for linters

---

app/models/config/base.rb
app/models/config/coffee_script.rb
app/models/config/eslint.rb
app/models/config/flake8.rb
app/models/config/haml.rb
app/models/config/jshint.rb
app/models/config/remark.rb
app/models/config/rubocop.rb
app/models/config/sass_lint.rb
app/models/config/scss.rb
app/models/config/shellcheck.rb
app/models/config/slim_lint.rb
app/models/config/stylelint.rb
app/models/config/swift.rb
app/models/config/tslint.rb
app/models/linter/base.rb
app/models/linter/flog.rb
spec/models/config/base_spec.rb
spec/models/linter/flog_spec.rb

Nothing ever was passing a parameter to `#serialize`.

Simplify linter's #serialize method

---

app/models/linter/flog.rb
spec/models/linter/flog_spec.rb

It creates a lot of noise.
Generally, spec and test files are less concise due to verbosity of
them.

Don't run Flog on spec/test files

---

app/assets/stylesheets/pages/repos/_organization.scss
app/assets/stylesheets/pages/repos/_tools.scss
app/javascript/__tests__/__snapshots__/repo_tools-test.jsx.snap
app/javascript/components/ReposContainer/components/RepoTools.jsx

The two buttons aren't related to the search, and they don't need to be
pressed for the search to happen. Thus, I think it makes sense to have
the searchbar live on its own line.
Also, don't hide "Include private repos" button on small screens
(phones).

Show searchbar on its own line

---

app/javascript/components/ReposContainer/components/Organization/OrganizationConfiguration.jsx

If the current org-wide config repository is not in the list of the
repos (for whatever reason), it won't be included in the dropdown list
of possible repos for org-wide configuration. This will cause us to
select another/different repo for org-wide config automatically,
effectively changing the org-wide config on the user.
This ensures the current org-wide config is always in that list.

Ensure presence of current org-wide config option

---

app/views/accounts/show.haml

These stats slow down the account page and occasionally time out. If customers find them useful we should cache the stats or deliver through a digest email or something similar.

Remove build stats from Account page

---

app/jobs/buildable.rb
app/services/start_build.rb
spec/jobs/buildable_spec.rb
spec/models/github_event_spec.rb
spec/services/start_build_spec.rb

It follows more of our convestion of naming services after what they do,
using a verb first. For example, `CreateRepo` or `SubmitReview`.
`StartBuild` fits nicely with the `CompleteBuild` service that we have.

Rename BuilRunner to StartBuild

---

app/services/review_files.rb
app/services/start_build.rb
doc/SECURITY.md
spec/services/review_files_spec.rb
spec/services/start_build_spec.rb

To follow the convention of naming our services with verb/action first.
`ReviewFiles` describes what this class does well.

Rename StyleChecker to ReviewFiles

---

config/locales/en.yml

Hound is redundant when used in the payment issue status message.
**Before**

Simplify payment failure status

---

app/models/linter/base.rb
app/models/linter/coffeelint.rb
app/models/linter/credo.rb
app/models/linter/eslint.rb
app/models/linter/flog.rb
app/models/linter/golint.rb
app/models/linter/haml_lint.rb
app/models/linter/jshint.rb
app/models/linter/reek.rb
app/models/linter/remark.rb
app/models/linter/rubocop.rb
app/models/linter/sass_lint.rb
app/models/linter/scss_lint.rb
app/models/linter/shellcheck.rb
app/models/linter/slim_lint.rb
app/models/linter/stylelint.rb
app/models/linter/swiftlint.rb
app/models/linter/tslint.rb
spec/models/linter/base_spec.rb

Only a handful of linters still queue to their specific queues.
Everything else is moving to the `linters` queue.

Default LintersJob as the default job for linters

---

.hound.yml
.reek

Our team didn't find the violations from them useful, but rather noisy.

Disable Reek and Flog

---

app/models/config/rubocop.rb
app/services/complete_file_review.rb
spec/models/config/coffeelint_spec.rb
spec/models/config/rubocop_spec.rb

We haven't seen any captures of legacy Hound config,
so we can assume nobody is using it anymore and cleanup the code.
Cleanup additional legacy logic.

 Remove handling of legacy config

---

app/jobs/buildable.rb
app/jobs/retryable.rb
spec/jobs/retryable_spec.rb

This will reduce the noise of exceptions that we get.
We currently report a general Sentry notification when we can't set the
status.
Additionally, some open source repos cannot be reviewed if we don't have
a valid token for them (all user tokens have become invalid or expired),
because we can't set their status.
With this change, we'll be able to review them and make comments on
violations, even though we cannot set the status.

Suppress error about failure to set GH status

---

Procfile

This should help keep up with spikes in `high` jobs.

Process high jobs if medium and low queues are empty

---

app/services/repo_subscriber.rb
spec/services/repo_subscriber_spec.rb

A uniqueness constraint prevented a `subscriptions` record from being created, which lead to the Stripe subscription being deleted. This change adjusts the way we deal with cleaning up Stripe subscriptions if there's an issue on our side (uniqueness constraint, etc.). Now we don't attempt to clean up the Stripe subscription when there's an exception.

Don't delete Stripe subscription when creation fails

---

CONTRIBUTING.md
README.md

👋 Hey there,
This PR completes @aldesantis and @gylaz work done into #1641 to allow linting ERB files by adding some documentation around this new addition. 
Since I have no access to the `houndci/linters` repo, in the PR I assumed that:
- ERB linting is done with [this tool](https://github.com/Shopify/erb-lint)
- linter code is located into `lib/linters/erb_lint`
- ~default config is located into `config/erb.yml`~
Let me know if I should change something.
Also, I think you should add an ERB help page (similar to [this one](https://intercom.help/hound/configuration/haml)) and update the [supported-linters](http://help.houndci.com/configuration/supported-linters) page as well. Let me know if I can be of help here.

Add more doc for ERB-Lint

---

app/jobs/completed_file_review_job.rb

If there's an `ActiveRecord::RecordNotFound` the jobs will retry
forever. We should only retry the `retry_attempts` times

Limit retry attempts of complete file reviews

---

README.md

- Python support added in #853 ~Aug 2015
- PHP support added in #1638 ~Jan 2019
I also alphabetized the core languages and indented the "dialects" like TypeScript and CoffeeScript to make scanning the list easier.

List Python and PHP in "Supported Languages"

---

config/routes.rb

To follow the `/jobs` path and other variables that start with `JOB_`.

Rename Sidekiq UI password variable

---

app/jobs/credo_review_job.rb
app/jobs/eslint_review_job.rb
app/jobs/flog_review_job.rb
app/jobs/jshint_review_job.rb
app/jobs/reek_review_job.rb
app/jobs/tslint_review_job.rb
app/models/linter/base.rb
app/models/linter/credo.rb
app/models/linter/eslint.rb
app/models/linter/flog.rb
app/models/linter/jshint.rb
app/models/linter/reek.rb
app/models/linter/tslint.rb
spec/models/linter/eslint_spec.rb
spec/models/linter/flog_spec.rb
spec/models/linter/jshint_spec.rb
spec/models/linter/tslint_spec.rb

We should be using the `linters` queue for all linters.

Use linters queue for all linter jobs

---

app/controllers/admin/job_failures_controller.rb
app/models/job_failure.rb
spec/models/job_failure_spec.rb

This reducers the noise on the `/admin/job_failures` page, and let's us
focus on more important failures.

Group dead jobs that failed due to setting status

---

config/locales/en.yml

This PR is not fixing any bugs and it is not adding any additional features. It is simply updating the copy of one of the Hound status texts to something more canine related.

Update copy for `pending_status`

---

app/models/config/base.rb
app/models/config/credo.rb
app/models/config/flog.rb
app/models/config/phpcs.rb
spec/features/user_deactivates_a_repo_spec.rb
spec/models/linter/go_spec.rb

Otherwise, the config was being serialized as a literal empty hash,
while most of the configs are servialized to text (then parsed on the
`linters` side).
This fixes an error reported by the `linters`.

Serialize empty configs as empty strings

---

app/views/application/_settings.haml
app/views/plans/index.html.haml

We currently are calling Stripe on each page load/reload to fetch the
user billable email.
This email is only needed during Plan purchase/upgrade.
Currently, Stripe API is having issues and our pages won't load.

Don't get the email from Stripe on every page

---

app/models/linter/eslint.rb
spec/models/linter/eslint_spec.rb

Add TS and TSX support to ESLint.
Typescript linting has been done in the past by TSLint, which is now being deprecated. The TSLint team [is pointing users to use @typescript-eslint ](https://medium.com/palantir/tslint-in-2019-1a144c2317a9)for typescript support; the Microsoft Typescript team, themselves, have been [transferring their linting capabilities to use ESLint](https://github.com/microsoft/TypeScript/issues/30553).
If users do not want their typescript files to be linted support they can simply add `*.ts` and `*.tsx` to their `.eslintignore` file.

Add .ts and .tsx support

---

config/initializers/omni_auth.rb

GitHub Apps don't use scopes, but OmniAuth GitHub library still needs
this option, to know to hit the GitHub API to fetch the email for the
user that is logging in.

Configure OmniAuth to get the GitHub user's email

---

app/controllers/application_controller.rb

We no longer have a `GET /auth/github`, so we should instead redirect
the user to the landing page.

Redirect to root when user is not authorized

---

config/initializers/omni_auth.rb

Logins are failing on Chrome and it seems due to receiving `GET`
requests. This is an attempt to get our logins working again.

Allow GET request for omniauth gem

---

app/policies/commenting_policy.rb
app/services/submit_review.rb
lib/github_api.rb
spec/policies/commenting_policy_spec.rb
spec/requests/builds_spec.rb
spec/requests/github_events_spec.rb
spec/services/submit_review_spec.rb
spec/support/fake_github.rb

To clean up the violation comments that have been addressed/outdated,
we will delete them from the PR. This will only be done for GitHub app
users, since each installation gets its own pool of API limits.

Delete outdated comments

---

app/services/submit_review.rb

Currently, we will only delete outdated violations if other violations
were found. Moving this logic out of that condition, will ensure we
cleanup outdated comments regardless of finding new violations.

Delete outdated comments without new violations

---

app/presenters/account_page.rb
app/views/application/_app_nav.haml

We attempt to call `recent_builds.count` but the method itself returns the count.

Fix recent_builds and its count

---

app/models/user.rb

Look for first user's subscription first, then look for any active repo.
Sometimes a user may still have a subscription, but it doesn't show up
in the list of user's repos.

Improve detection of first repo for user

---

Gemfile.lock

Update websocket-extensions to v0.1.5

---

app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_pricing.scss
app/assets/stylesheets/pages/_docs.scss
app/assets/stylesheets/pages/home/_home-configuration.scss
app/assets/stylesheets/pages/home/_home-hero.scss
app/assets/stylesheets/pages/home/_home-importance.scss
app/assets/stylesheets/pages/home/_home-languages.scss
app/assets/stylesheets/pages/home/_home-objects.scss
app/assets/stylesheets/pages/home/_home-pricing.scss
app/assets/stylesheets/pages/home/_home-value.scss
app/assets/stylesheets/pages/repos/_index.scss
app/assets/stylesheets/pages/repos/_onboarding.scss
app/assets/stylesheets/pages/repos/_organization.scss
app/assets/stylesheets/pages/repos/_tools.scss

Neat is no longer maintained. This commit starts to remove Neat by
replacing almost all instances of its `media` mixin with vanilla CSS
syntax - there really is no need for a mixin here.

Replace Neat `media` mixin with vanilla CSS

---

app/helpers/application_helper.rb
app/views/application/_app_nav.haml
app/views/layouts/application.haml

`https://github.com/<username>.png` will return a user or organization’s
avatar. It’s been written about on the GitHub Blog:
https://github.blog/2020-04-16-github-protips-tips-tricks-hacks-and-secrets-from-jason-etcovitch/#get-a-user-or-organizations-avatar
The `preconnect` is added to establish a connection to github.com
early, increasing perceived image loading performance.
No visual changes (beyond the fact that someone’s avatar will switch to their 
GitHub one, if it’s not the same as their Gravatar)

Pull avatars from GitHub instead of Gravatar

---

app/assets/stylesheets/pages/home/_home-objects.scss

By default, all `p` elements have some bottom margin, but on the
home page, we were overriding that with `margin: 0;` - that was done
using an overly-specific selector _and_ by using the `margin` shorthand:
https://github.com/houndci/hound/blob/5cdb8ec492d77aa2cf4f566e3f6b17f2f389ab54/app/assets/stylesheets/pages/home/_home-objects.scss#L15-L17
This meant our `margin-top-large` utility class was not working.
Part of this problem is what is called an ‘accidental reset’: https://css-tricks.com/accidental-css-resets/
By only setting the `margin-bottom`, we are only resetting the exact 
piece we want to reset, not _all_ margins.

Fix missing margin

---

app/views/application/_footer.haml
app/views/layouts/application.html.erb

Resolves two HTML validation errors:
1. Element `meta` is missing one or more of the following attributes: `http-equiv`, `itemprop`, `name`, `property`.
1. Bad value `https://twitter.com/share?text=@houndci &url=""` for attribute `href` on element `a`: Illegal character in query: space is not allowed.

Fix HTML validation errors

---

Gemfile.lock
app/models/plan_selector.rb
app/models/repo.rb
spec/models/plan_selector_spec.rb
spec/models/user_spec.rb
spec/services/repo_subscriber_spec.rb

If a user has access to the repo and the owner of what repo has been
granted a whitelist/bulk permission, then it should be activatable.

Allow any user to upgrade whitelisted repos

---

app/javascript/components/ReposContainer/components/App.jsx
app/services/repo_subscriber.rb
spec/services/repo_subscriber_spec.rb

If an org (that a given repo belongs to) already has paid/subscribed
repos, we will now use that Stripe account to allow enabling another
paid repo under that Strip account. This should prevent users from same
GitHub orgs needing to create new Stripe accounts to enable more repos.

Activate repo with existing stripe customer

---

app/services/repo_subscriber.rb
spec/services/repo_subscriber_spec.rb

This fixes the logic where a user that activates a repo already has a
Stripe account, but it's not set-up for being charged (older users).
We now will try to find an existing paying user within the same org,
before checking if the current user has a Stripe account.

Look for existing paying Stripe user first

---

app/models/github_event.rb
config/initializers/sidekiq.rb

Heroku will be upgrading our Redis to 7.0, which also means we need to switch to SSL connection.

Enable Redis TLS in Sidekiq
